### ISSUE TITLE
Giant blocks render as a cube of smaller blocks

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#1]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38

Steps to reproduce:
1. Place any giant block

What I expected to happen:
The giant blocks would look like a 4x larger version of their regular form, as I remember them looking in 1.7.10.

What happened instead:
The giant blocks look like this:
![2021-09-22_19 32 42](https://user-images.githubusercontent.com/69029346/134447035-4d6e871f-658f-49cd-a7f3-bc0c3a9eb7e0.png)

**Comment by Dragon-Seeker** [comment]
Its a current bug with the 1.17 forge version also.
