### ISSUE TITLE
Getting hit by a shulker bullet crashes the game

### ISSUE THREAD

**Issue by notmaroun** [TeamTwilight/twilightforest-fabric#100]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.57.0+1.18.2

### Twilight Forest Version

1.18.2-4.1.251

### Crash Report (if applicable)

https://gist.github.com/notmaroun/ad6cd034c425440f81487dca26f49eb0

### Steps to Reproduce

Hello, getting hit by a shulker bullet when wearing certain fire armours seems to crash the server. This seems to be a known issue on the Discord server, just posting this here for completeness. I believe this has been patched on the Forge version.

### What You Expected

It... Not crashing?

### What Happened Instead

The server crashing.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
this has been fixed
