### ISSUE TITLE
Server console error

### ISSUE THREAD

**Issue by Dr-WeiAL** [TeamTwilight/twilightforest-fabric#102]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.57.0

### Twilight Forest Version

4.1.251

### Steps to Reproduce

In the server, don't know what's going on
[2022-07-21-1.log](https://github.com/TeamTwilight/twilightforest-fabric/files/9155069/2022-07-21-1.log)

### What You Expected

don't report an error

### What Happened Instead

Console error causes tps to be greatly reduced

### Additional Details

Repeat prompt
[Server thread/WARN]: Still did not find a safe portal spot.
[Server thread/INFO]: Did not find a safe portal spot at first try, trying again with longer range.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Its just a warning
