### ISSUE TITLE
java.lang.RuntimeException: Error building entry twilightforest:world/portal

### ISSUE THREAD

**Issue by TheButterbrotMan** [TeamTwilight/twilightforest-fabric#103]
### Fabric Loader Version

0.14.8

### Fabric API Version

fabric-api-0.58.0+1.18.2

### Twilight Forest Version

twilightforest-fabric-1.18.2-4.1.251

### Client Log

https://bytebin.lucko.me/FmKkX71uVP

### Steps to Reproduce

Sadly i dont know a way to reproduce.

### What You Expected

Doesnt fail to connect.

### What Happened Instead

Fails to connect.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [ ] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Geethebluesky** [comment]
I'm getting the same error, which occurs after loading a world. I made a new PolyMC instance with minimal mods (just the visual ones like Sodium etc. and  performance-enhancing ones like FerriteCore, Lithium, etc.) to test.

It looks like Twilight Forest and Patchouli aren't interacting well together (?)
I'm not sure what this affects but I can at least reproduce the issue.


**Fabric Loader Version** : 0.14.9
**Fabric API Version**: fabric-api-0.58.0+1.18.2
**Twilight Forest Version**: twilightforest-fabric-1.18.2-4.1.268

**Client Log**: https://pastebin.com/zVAfCrk7

**Crash Report (if applicable)**: Begins at line 352 of the latest.log pasted above

**Steps to Reproduce**
- Set up a brand new MC 1.18.2 + Fabric instance
- Add Twilight Forest and Patchouli with their dependencies
- Create a world
- Load the world.
That's it, it happens every time.


**Additional info**:
- I haven't tried this on Forge, I never play on Forge anymore.
- I do have Sodium etc. installed but doesn't seem like that matters here. (??)

**Comment by alfonsan** [comment]
I'm still having this exact same problem at:

Forge: 1.18.2, 40.1.80
Twilight Forest: 4.1.1423
Patchouli: 71.1.

**Comment by Aquaeyes** [comment]
Looks to be an issue with Terrablender compat, removing it fixed the issue for me.

**Comment by Dragon-Seeker** [comment]
https://github.com/TeamTwilight/twilightforest-fabric/blob/adcb478daf1dd99497803680fecfbba0dd43a829/src/main/resources/data/twilightforest/patchouli_books/guide/en_us/entries/world/portal.json#L36 Seems to be an issue with the tag not being read maybe...

**Comment by TropheusJ** [comment]
the patchouli book has been removed in 1.19+.
