### ISSUE TITLE
Feature Placement Failure

### ISSUE THREAD

**Issue by FluffyBumblebees** [TeamTwilight/twilightforest-fabric#104]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.58+1.18.2

### Twilight Forest Version

4.1-251

### Client Log

https://gist.github.com/FluffyBumblebees/f8680c9e203f9cc55273a4516ba0c429

### Steps to Reproduce

1. Install this modpack https://www.technicpack.net/modpack/the-limit-reborn-1181.1905659
2. Install TF
3. Enter the TF dimension via the portal
4. Chaos

### What You Expected

For Feature placement to work correctly

### What Happened Instead

Internal Server Closes, then log spam. There isn't an actual crash report

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by FluffyBumblebees** [comment]
Alright, I confirmed that it is C2ME causing this

**Comment by FluffyBumblebees** [comment]
Ishland says its fixed in the latest dev build. Will reopen if issue persists

**Comment by FluffyBumblebees** [comment]
Yep, It's still fucked

**Comment by TropheusJ** [comment]
closing in favor of #139
