### ISSUE TITLE
Config Option skylightForest does not work

### ISSUE THREAD

**Issue by MSandro** [TeamTwilight/twilightforest-fabric#105]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.58.0

### Twilight Forest Version

4.1.251

### Steps to Reproduce

* set skylightForest to true in the config file.
* start minecraft
* create a new world
* enter the Dimension
* no sky world :(

### What You Expected

it should just generate the structures. like descibed in the Config file!

### What Happened Instead

it generates the surface

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by MSandro** [comment]
![image](https://user-images.githubusercontent.com/10937159/181244202-ba27e9e7-c7e2-4f21-8296-688b868ff735.png)
Is there a DataPack to enable it?
I found the skylight_noise_gen and configured it in the dimension/twilight_forest.json, but It doesn't look as expected.

**Comment by 0gp** [comment]
any help? I can't activate it either. I've already spent 2 hours trying to access it via datapack.

**Comment by AlphaMode** [comment]
The skylight forest is unfinished and has been removed in 1.19
