### ISSUE TITLE
Structures are way to common

### ISSUE THREAD

**Issue by Gishiki3** [TeamTwilight/twilightforest-fabric#108]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.58.0

### Twilight Forest Version

4.1.268

### Client Log

<script src="https://gist.github.com/Gishiki3/80af2c31fb9738f1f74486afbdd2c43a.js"></script>

### Steps to Reproduce

1. Load world
2. Play World
3. 3 enter Twilight Forest

### What You Expected

Structures to be somewhat rare with most being large structures being a decent ways away from eachother

### What Happened Instead

Literally 2 end castles within render distance of eachother and also lots of structures scattered within veiw of eachother.

### Additional Details

Below I've attached screenshots I consider relevant to this. Additionally I'd like to mention I am playing with other mods, but I disabled the only mod that I know affects other dimensions (BClib) and the issue was still present.
![2022-08-01_16 06 01](https://user-images.githubusercontent.com/110432441/182267406-aefdd617-2fb6-43b2-aa26-a453a9059def.png)
![2022-08-01_17 24 41](https://user-images.githubusercontent.com/110432441/182267412-365c7ddf-e342-4f94-b030-b519d8076163.png)
![2022-08-01_17 25 09](https://user-images.githubusercontent.com/110432441/182267419-44be0737-7d6c-46f4-a088-27a61a9115f7.png)
![2022-08-01_17 25 51](https://user-images.githubusercontent.com/110432441/182267423-2ba8c58f-56e0-4ceb-82cd-814cb9b05f8e.png)
![2022-08-01_17 30 16](https://user-images.githubusercontent.com/110432441/182267426-2a48bd11-03ce-4e8b-b8cf-3ce935268666.png)
![2022-08-01_17 30 39](https://user-images.githubusercontent.com/110432441/182267429-3b11d0fa-e409-43ff-9a45-93280f7109ee.png)
![2022-08-01_16 05 23](https://user-images.githubusercontent.com/110432441/182267400-883feb1f-eb05-47f2-9527-fabe871369e4.png)
![2022-08-01_16 05 48](https://user-images.githubusercontent.com/110432441/182267405-69b59526-b0a5-4a01-a95c-3db7a5c7dd1b.png)
![2022-08-01_15 59 13](https://user-images.githubusercontent.com/110432441/182267392-d58dadb8-895c-441c-ab35-60f68ac58ea9.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
this is how TF's structure and biome layout works, this isnt a bug
