### ISSUE TITLE
Canvas + Twilight 

### ISSUE THREAD

**Issue by CalixWorhad** [TeamTwilight/twilightforest-fabric#109]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.58.0

### Twilight Forest Version

4.1.251

### Steps to Reproduce

1. Create Twilight Portal
2. Go inside portal

### What You Expected

I thought that the portal would just take me and my friends to the twilight realm without too much trouble.

### What Happened Instead

We became stuck until Canvas was uninstalled.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by grondag** [comment]
This needs fixing on my end.  Canvas isn't supporting the newish Fabric dimension render hooks as it should.

**Comment by Dragon-Seeker** [comment]
@CalixWorhad Have you tested if such happens anymore?

**Comment by TropheusJ** [comment]
seems grondag fixed it
