### ISSUE TITLE
[Suggestion] 

### ISSUE THREAD

**Issue by heyjudek** [TeamTwilight/twilightforest-fabric#110]
### The Suggestion

Perpendicular Banisters do not connect properly and one of their sides gets culled incorrectly when there is an adjacent non-full block.
![2022-08-10_20 58 24](https://user-images.githubusercontent.com/74119394/183973623-7cfae6f3-fc70-4ff4-b0db-9d16f086ecc0.png)
 

### Why Should It Be in the Mod?

Better texture quality.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
This doesn't happen in the base mod. If you have a performance mod like sodium I'm pretty sure that's what causes the issue. (It happens with Rubidium on forge)

**Comment by heyjudek** [comment]
Thank you for the input. What about the second issue though? Even in the base mod, if you put two banisters at a perpendicular way, there is going to be a gap between then. Is there a way to make it so that the third banister placed there just act like a post and "connects" those two?
