### ISSUE TITLE
Concurrent Modification Exception/Feature Placement crash

### ISSUE THREAD

**Issue by cybercat5555** [TeamTwilight/twilightforest-fabric#113]
### Fabric Loader Version

0.14.8

### Fabric API Version

fabric-api-0.58.0+1.18.2

### Twilight Forest Version

twilightforest-fabric-1.18.2-4.1.268

### Crash Report (if applicable)

https://gist.github.com/cybercat5555/7e2a2b4a2687bad50660de7e16041441

### Steps to Reproduce

1. Enter the Twilight Forest
2. Explore around 
3. Crash when this fires

### What You Expected

That this would not crash and the tree could be placed safely

### What Happened Instead

The game crashes upon placement

### Additional Details

This crash occurs each time the bugged area is accessed, it doesn't become "safe" or anything after the crash.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Do you have C2ME installed?

**Comment by cybercat5555** [comment]
I do not have it, nor any mod that depends on it

**Comment by FluffyBumblebees** [comment]
C2me is installed… the log says so

**Comment by FluffyBumblebees** [comment]
Duplicate of my issue

**Comment by AlphaMode** [comment]
Duplicate of #104

**Comment by cybercat5555** [comment]
C2me seems to be pre-packaged in another mod, rather than a "normal" dep. Is there any way to tell which mod is using it?

**Comment by FluffyBumblebees** [comment]
embedded libraries appeared like this:
- normal mod
- embedded lib **via** normal mod

**Comment by FluffyBumblebees** [comment]
It looks like it's in there as normal as one would add it.

**Comment by cybercat5555** [comment]
Ah, my bad. One of the other admins on the server added c2me without documenting it, sorry about that lol

**Comment by FluffyBumblebees** [comment]
C2ME can be used with this mod, just get the admin to disable multithreaded feature generation
