### ISSUE TITLE
excessive giants in the giants cottage

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest-fabric#12]
### Forge Version

0.11.7

### Twilight Forest Version

4.0.69

### Steps to Reproduce

there were an excessive amount of giants at the giant cottage.
![2021-10-03_18 33 32](https://user-images.githubusercontent.com/68449401/135775658-d256c0ba-1b40-4516-b9df-eca15a058acb.png)

### What You Expected

there to be one of each

### What Happened Instead

there was a few miners and almost a dozen armored giants

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by AlphaMode** [comment]
Have you checked if this happens on forge?
