### ISSUE TITLE
All of Fabric 5 - Block ID conflict - Cross Post

### ISSUE THREAD

**Issue by GayKiwi** [TeamTwilight/twilightforest-fabric#120]
### Fabric Loader Version

0.14.9

### Fabric API Version

0.58.0

### Twilight Forest Version

4.1.268

### Steps to Reproduce

All of Fabric 1.5.1

Roughly Enough Items - search for **Mythical Mounts**
Recipe shown tells you how to craft **Traveller's Logbook [WIP]**

Conflict because
**Traveller's Logbook [WIP]** uses block id **patchouli:guide_book**
**Mythical Mounts** uses block id **patchouli:guide_book**

### What You Expected

Unique block id's for each guide book.

### What Happened Instead

Only one guide book can be crafted by the user.

### Additional Details

This is a cross post from both All of Fabric 5, and Mythical Mounts, and by the same user.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
the guide book has been removed in newer versions.
