### ISSUE TITLE
Doesn't work in Fabric Modpack "Survival - Tools"

### ISSUE THREAD

**Issue by adorableboiz** [TeamTwilight/twilightforest-fabric#122]
### Fabric Loader Version

0.14.9

### Fabric API Version

0.61.0+1.19.2

### Twilight Forest Version

4.2.1392

### Steps to Reproduce

1. Installed Twilight Forest into Modpack
2. Open client
3. Open Mods Option
4. Twilight Forest Mod not shown

### What You Expected

Twilight Forest should be shown in the Mod Option and inside the game

### What Happened Instead

Twilight Forest didn't operate properly, and there is nothing related shown in JEI

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
You didn't install the mod properly and the mod isn't even ready for testing
