### ISSUE TITLE
the mod crashes without a crash report

### ISSUE THREAD

**Issue by DoctorFrank28** [TeamTwilight/twilightforest-fabric#124]
### Fabric Loader Version

0.14.9

### Fabric API Version

0.62.0

### Twilight Forest Version

4.2.299

### Client Log

https://gist.github.com/DoctorFrank28/395babf0a3f6cf71d5581253c4f9a4bc

### Steps to Reproduce

1 Download betterMinecraft 1.19.2. v7
2 Add twilight forest

### What You Expected

.

### What Happened Instead

it crashes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Remove DashLoader it's not longer being maintained

**Comment by icedcaveVF** [comment]
I am having the exact same issue, I removed dashloader and nothing has changed

**Comment by axijiku** [comment]
I'm also having this same issue, installed it fresh even with optional dependencies and my minecraft crashes without any log available.
