### ISSUE TITLE
Quilt loader fails to load accessors jar from this mod, crashes on startup

### ISSUE THREAD

**Issue by FyreAlchemage** [TeamTwilight/twilightforest-fabric#126]
### Fabric Loader Version

Quilt 0.17.4

### Fabric API Version

Quilted Fabric API 4.0.0-beta.13+0.62.0+1.19.2

### Twilight Forest Version

4.2.299

### Client Log

https://gist.github.com/FyreAlchemage/08e6e4cd3990d06a2a7aa88d0d396b1a

### Steps to Reproduce

Install Quilt, add Twilight Forest, observe crash. (I did test this on an instance running the same loader and versions without any other mods, and observed the same result)

### What You Expected

I expected the mod to load with no errors, or at least with an error I could understand.

### What Happened Instead

The game fails to load, claiming it cannot load an accessors jar into memory.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
this has been fixed for a while
