### ISSUE TITLE
Charm Of Keeping Deletes items when paired with a totem of undying.

### ISSUE THREAD

**Issue by InfidelKilla** [TeamTwilight/twilightforest-fabric#127]
### Fabric Loader Version

0.14.10

### Fabric API Version

fabric-api-0.64.0+1.19.2.jar

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.301.jar

### Steps to Reproduce

Step 1. Use the trinkets mod alongside with the charm trinket mod.
Step 2. Place a totem in the charm trinket slot and the charm of keeping 2 in the belt trinket slot.
Step 3. Die to something in survival. Make sure to place items in your hotbar and inventory and your armor slots.

### What You Expected

I expected for the totem of undying to pop first followed by the charm of keeping 2. 

### What Happened Instead

But instead they both popped at once and it deleted the items in my hotbar and in my armor slots. It may also affect the trinket slots. 

### Additional Details

This may happen with all charms of keeping and with the totem in the offhand or mainhand instead of the charm trinket slot. This could also affect other charms provided by twilight forest. It could be that the method is out of order and prioritizes twilight forest charms over vanilla when it should be the opposite. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by InfidelKilla** [comment]
I can a youtube video if necessary that shows what happens.

**Comment by TropheusJ** [comment]
seems to be fixed
