### ISSUE TITLE
How can i config this?

### ISSUE THREAD

**Issue by jarocajavi** [TeamTwilight/twilightforest-fabric#129]
Hello, how can i use the config file for add an item to can't uncraft it

`	#If an item has multiple crafting recipes and you wish to disable them all, add the item to the "twilightforest:banned_uncraftables" item tag.
	#If you have a problematic ingredient, like infested towerwood for example, add the item to the "twilightforest:banned_uncrafting_ingredients" item tag.
	disableUncraftingRecipes = ["techreborn:banned_uu_matter"]`

I don't know if i understand the format, can you halp me?

Thanks so much

**Comment by TropheusJ** [comment]
items can be added to the tags through datapacks. if you need help with datapacks, see the minecraft wiki.
