### ISSUE TITLE
[1.19.2] Issue with Luggages Version of Forge Tags

### ISSUE THREAD

**Issue by Poke097** [TeamTwilight/twilightforest-fabric#131]
### Fabric Loader Version

0.14.10

### Fabric API Version

fabric-api-0.64.0+1.19.2

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.301

### Client Log

https://gist.github.com/Poke097/81dbbcfd14026f7389442ed8ffaaaa4b

### Crash Report (if applicable)

https://gist.github.com/Poke097/a5f592cf4e9c0c45f4982b9c28f947cb

### Steps to Reproduce

1. Go into the snowy forest

2. Encounter a yeti

3. Will crash game randomly

### What You Expected

To not crash when going into the biome with the Yeti's

### What Happened Instead

Crashed server when trying to render Yeti

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Dragon-Seeker** [comment]
This is an issue with Luggaes version of Forge Tags being out of date leading to the old version taking precedence causing the EntityType Tags to be non existant.

**Comment by AlphaMode** [comment]
Fixed in latest release of luggage
