### ISSUE TITLE
Tombstone won't return my stuff

### ISSUE THREAD

**Issue by Neji19** [TeamTwilight/twilightforest-fabric#132]
### Fabric Loader Version

0.14.9

### Fabric API Version

1.19.2 v9.zip

### Twilight Forest Version

4.2.299

### Steps to Reproduce

i died in my minecraft world and wanted to get my stuff back from my tombstone but when i clicked on tombstone i didn't get my loot back.

### What You Expected

I expected to get my stuff back

### What Happened Instead

my stuff is gone

### Additional Details

I play on a modpack called Better MC on version 1.19.2

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
Gravestone issues seem to be fixed in dev.
