### ISSUE TITLE
World generation crash (TFGenCanopyOak, TFTreeGenerator)

### ISSUE THREAD

**Issue by serega404** [TeamTwilight/twilightforest-fabric#133]
### Fabric Loader Version

0.14.9

### Fabric API Version

0.58.0+1.18.2

### Twilight Forest Version

4.1.268

### Crash Report (if applicable)

https://gist.github.com/serega404/f1a114796c57ccc7f677e110357907a5

### Steps to Reproduce

1. Build portal
2. Enter portal

### What You Expected

Server doesn't crash

### What Happened Instead

Server crash

### Additional Details

There were failures before, too, but it was so long ago that the logs were not preserved, after two failures the world worked quietly in one place. Today, players who are far away from this place have created a portal and created fragments of the twilight forest world. 

I ticked the box that I checked it on forge, but it's not, this bug is extremely easy to catch when using the basic tf functionality, so I went to check issues in the forge version repository, I couldn't find a similar problem (I searched for the TFTreeGenerator, TFGenCanopyOak classes)

(machine translation)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Your issue is likely caused by C2ME if you have it installed next time please provide a full log with a mod list

**Comment by serega404** [comment]
[Full log](https://gist.github.com/serega404/8f8de7d1e5bb99f3810138264f1a55af), mods inside

**Comment by AlphaMode** [comment]
The issue is a duplicate of #104 just remove c2me and it should work fine.

**Comment by serega404** [comment]
Should I report this issue to the C2ME developers?

**Comment by AlphaMode** [comment]
I'm pretty sure they already know, and I think this is actually up to TF to fix but the problem is that the changes should be done on the forge version which I'm not in charge of.
