### ISSUE TITLE
[Suggestion] Fix list iterations to get a list of all the mobs in a given structure being extremely laggy

### ISSUE THREAD

**Issue by CookieGD** [TeamTwilight/twilightforest-fabric#136]
### The Suggestion

I play the All Of Fabric 5 modpack and I noticed that Twilight Forest is causing quite bad issues with server TPS when close to structures like the Lichen (that skeleton boss) Tower. After looking at the Spark Profile that I generated with _/spark profiler_ I noticed that Twilight Forest took up ~78% of server threads, specifically for mob related stuff. I asked in the TeamAOF server what to do and they suggested me to go to this github page and open an issue. So here I am asking you to please fix this issue!

Modpack version: 2.0.5
Twilight Forest version: 4.1.268
Fabric version: 0.14.9
Fabric API version: 0.59.1+1.18.2

Spark profile: https://spark.lucko.me/qtYbXWi4z3

### Why Should It Be in the Mod?

TPS issues are no fun and I think the above-mentioned issue can be fixed.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Dragon-Seeker** [comment]
A fix was [pushed](https://github.com/TeamTwilight/twilightforest-fabric/commit/e1ca40739f9e0f5edb766e0bf63287a7e2f5de66) to the 1.18.2 Branch but we are no longer supporting the 1.18.2 Version at this moment.
