### ISSUE TITLE
Final Castle generation occasionally causes a crash

### ISSUE THREAD

**Issue by karyeet** [TeamTwilight/twilightforest-fabric#140]
### Fabric Loader Version

0.14.10

### Fabric API Version

0.64.0+1.19.2

### Twilight Forest Version

1.19.2-4.2.310

### Client Log

https://gist.github.com/karyeet/d2df326df66cf1c87d3054236e79b169

### Crash Report (if applicable)

https://gist.github.com/karyeet/21843dacfc54c16cecc08b31dbdc6f17

### Steps to Reproduce

1. Enter Twilight Forest dimension
2. Walk around & generate new chunks
3. Find/get near lich tower?

### What You Expected

The server not to crash.

### What Happened Instead

Server will close and console will show crash, but process will not end.

### Additional Details

This was using Better Minecraft Modpack for Fabric 1.19.2 on a server.
I tried with the shipped version of twilight forest and the previously stated version, which was latest on curseforge.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by karyeet** [comment]
Issue persists with fabric-api-0.66.0+1.19.2

**Comment by karyeet** [comment]
Issue was not present in a new world so I changed the seed of the current world's level.dat to the working world's seed (so that we can keep our buildings in the overworld) and the server no longer crashed.

working seed: `692547574664842009`

broken seed: `3795325739841307362`

**Comment by TropheusJ** [comment]
Happens on forge too: https://github.com/TeamTwilight/twilightforest/issues/1699

**Comment by wickedside** [comment]
Have the same bug on forge 1.19.2

**Comment by TheUnknownCod3r** [comment]
Still an issue as of the latest build. I know its fixed on Forge, so hopefully it'll be fixed soon on Fabric too.

**Comment by Killasaurus-Warbear** [comment]
Having this issue in fabric version 4.2.335 while trying to pregenerate with Chunky. Any chance there's a known workaround?

**Comment by TropheusJ** [comment]
fix has been merged into 1.19.2, will backport to 1.18.2

**Comment by Boroso** [comment]
this has not been fixed, see my latest issue

**Comment by TropheusJ** [comment]
it has been fixed, but the fixed version has not been published yet.
