### ISSUE TITLE
Porting Lib not loading, causing crash

### ISSUE THREAD

**Issue by varencilator** [TeamTwilight/twilightforest-fabric#143]
### Fabric Loader Version

0.14.10

### Fabric API Version

0.63.0

### Twilight Forest Version

4.2.310

### Client Log

https://gist.github.com/varencilator/62708de9b8ade1fa3f49fe3c1dd39c97

### Crash Report (if applicable)

https://gist.github.com/varencilator/189a4949a96ca9f3e0779f4da5c993c8

### Steps to Reproduce

Crashes on startup

### What You Expected

Launches properly

### What Happened Instead

Crashes

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
seems Porting Lib just isn't loading somehow? Try manually installing it from [here](https://modrinth.com/mod/porting_lib/version/2.1.627+1.19.2).

**Comment by TropheusJ** [comment]
This doesn't make any sense and I can't reproduce it. Try TF alone, and if it works, try to narrow down the cause.

**Comment by varencilator** [comment]
It started up properly when I manually installed Porting Lib so I guess this could be marked off as solved sort of as some one off occurrence if you can't replicate it.

Still encountered the known portal not working issue for the latest version.
