### ISSUE TITLE
Cannot create portal

### ISSUE THREAD

**Issue by Somiona** [TeamTwilight/twilightforest-fabric#144]
### Fabric Loader Version

0.14.10

### Fabric API Version

0.68.0

### Twilight Forest Version

4.2.310

### Client Log

https://gist.github.com/Somiona/696a86af879796d6d1c5238eaba2b053

### Steps to Reproduce

Build a portal as instruction, throw a diamond, but nothing happen.
![image](https://user-images.githubusercontent.com/20739885/205153174-457d9737-984e-4b97-bb47-b9e70303f35e.png)

### What You Expected

The water pool changes to a portal after throwing in a diamond

### What Happened Instead

Nothing happened after throwing in a diamond. I can confirm the water is still and config allows me to build a portal.

### Additional Details

I don't know if there's any mod incompatible with twilight forest, and I am not sure how to debug it. Please instruct me how to find the exactly one conflicting twilight forest, since there's no log produced when I throw a diamond and nothing happens.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SteveNichols5** [comment]
Confirmed same issue on Fabric 1.19.2 using version twilightforest-fabric-1.19.2-4.2.310.jar

**Comment by Somiona** [comment]
Confirmed one incompatibility between my very version of twilight forest with Create V0.5. The portal works fine after removing Create.

**Comment by durochal** [comment]
I know this was closed already, but is there anyone looking into actually fixing this?

**Comment by TropheusJ** [comment]
it is fixed, just not released yet
