### ISSUE TITLE
Portal not opening on newest version of mod

### ISSUE THREAD

**Issue by iTheAndromeda** [TeamTwilight/twilightforest-fabric#145]
### Fabric Loader Version

0.14.10

### Fabric API Version

0.68.0+1.19.2

### Twilight Forest Version

4.2.310

### Steps to Reproduce

1. Dig 2x2 hole in ground
2. Fill hole with water
3. Surround hole with vanilla Minecraft flowers
4. Throw diamond into water
5. Nothing happens

### What You Expected

I expected the portal to open when made correctly.

### What Happened Instead

The portal didn't open, the diamond just floated in the water.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
downgrade or remove Create, will be fixed in the next TF release
