### ISSUE TITLE
Charm of Keeping 3

### ISSUE THREAD

**Issue by alexbwkim** [TeamTwilight/twilightforest-fabric#146]
### Fabric Loader Version

0.14.11

### Fabric API Version

0.68.0+ 1.19.2

### Twilight Forest Version

4.2.310

### Steps to Reproduce

1. Have a charm of keeping 3
2. Die, overworld or any other dimension, doesn't matter
3. observe as charm of keeping circles player model
4. no items are returned

### What You Expected

I thought the inventory would be kept, or the items would spawn above the player. 

### What Happened Instead

The items are not returned, inventory remains empty. Items are not at death location either, perhaps deleted from world?

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
this has been fixed in dev versions
