### ISSUE TITLE
Incompatible with Create Fabric mod (portal doesn't work)

### ISSUE THREAD

**Issue by moitripa** [TeamTwilight/twilightforest-fabric#147]
### Fabric Loader Version

0.14.11 - 1.19.2

### Fabric API Version

0.69.0 - 1.19.2

### Twilight Forest Version

4.2.310 - 1.19.2

### Client Log

https://gist.github.com/moitripa/f2987315d93febf8a1d0c18bceecece0

### Steps to Reproduce

I try to create a Twilight Forest portal, it doesn't work, when Create Fabric mod is installed.

### What You Expected

The portal was supposed to be created when I throw a diamond.

### What Happened Instead

The portal is simply not created. Twilight Forest's creative tab and all of its items are intact and working just fine, so I know the mod is loaded. No crashes, just the portal not working.

### Additional Details

Create Fabric version: [Create 1.19.2 v0.5.0g Patch 1](https://www.curseforge.com/minecraft/mc-mods/create-fabric/files/4125637)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
already fixed in dev, you can downgrade Create 1 version in the meantime
