### ISSUE TITLE
untextured bean stalk

### ISSUE THREAD

**Issue by CobaltGlacier** [TeamTwilight/twilightforest-fabric#15]
### Forge Version

0.11.7

### Twilight Forest Version

4.0.69

### Steps to Reproduce

the bean stalk is untextured
![2021-10-03_18 43 29](https://user-images.githubusercontent.com/68449401/135775856-59d2145e-427e-470e-ad66-d5fc075dfc5e.png)

### What You Expected

for the bean stalk to be textured.

### What Happened Instead

no textures.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).

**Comment by saltyseadoggo** [comment]
This is fixed now.
