### ISSUE TITLE
Charm of Keeping deletes items when equipped and using the you're in grave danger mod.

### ISSUE THREAD

**Issue by ZelPie** [TeamTwilight/twilightforest-fabric#150]
### Fabric Loader Version

0.14.10

### Fabric API Version

0.68.0+1.19.2

### Twilight Forest Version

4.2.310

### Steps to Reproduce

1. Die while the charm of keeping is in your inventory of equipped in the belt slot.
2. Click respawn at which the charm should give you your items, but it does not.
3. Look around where you respawned and your items arent even dropped on the floor.
4. Check the grave, the items are not there either.

### What You Expected

We expected my cousin and sisters' items to be restored. It first happened to my cousin when he died so we all took the charms out of the belt slot, however my sister died after but the charm activated even by just being in her inventory (something I know most charms do but didn't think of at the time). 

### What Happened Instead

Instead, their items were deleted, and we looked everywhere and checked our spawn locations multiple times for dropped items and there wasn't anything.

### Additional Details

I've already reported this bug to the you're in grave danger mod devs as well, still waiting for a response there but I figured I should send a report here too. This wouldn't happen in the forge version as this specific grave mod does not have a forge version.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
update
