### ISSUE TITLE
[1.19.2] - Some uncrafting recipes doesn't work or gives ghost items

### ISSUE THREAD

**Issue by aking4125** [TeamTwilight/twilightforest-fabric#151]
### Fabric Loader Version

0.14.11

### Fabric API Version

0.68.0+1.19.2

### Twilight Forest Version

4.2.310

### Steps to Reproduce

Brown dye seems to be the easiest with Acacia saplings:

1. Place Acacia sapling into the Uncrafting table
2. Brown dye will appear for a moment, you can take it
3. Brown dye isn't actually real 

### What You Expected

To be able to uncraft Acacia saplings into brown dye as shown in REI.

Perhaps it's just a recipe error.

### What Happened Instead

https://www.xbox.com/en-US/play/media/NUSVUENNGS

### Additional Details

Using BetterMC (Fabric)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
looks to be resolved, broken recipes in the pack
