### ISSUE TITLE
Vivecraft & Twilight Forest Crash upon Block Chain Goblin sighting

### ISSUE THREAD

**Issue by Miv2nir** [TeamTwilight/twilightforest-fabric#158]
### Forge Version

40.2.0

### Twilight Forest Version

4.1.1423

### Client Log

https://gist.github.com/Miv2nir/c5f5c3f95fb557bf687aecb07a7bdb18

### Crash Report (if applicable)

https://gist.github.com/Miv2nir/1d8837d159056504ffb6b4193770334c

### Steps to Reproduce

1. Install Vivecraft alongside Twilight Forest.
2. Launch the world.
3. Spawn Block Chain Goblin or encounter it in the wild.
4. Observe the crash.

### What You Expected

For the game to not crash.

### What Happened Instead

The game crashed.

### Additional Details
Vivecraft version: 0.0.13

Exactly the same issue happens with Fabric ports of both mods.
Fabric Loader Version: 0.14.12
Fabric API Version: 0.67.0+1.18.2
Twilight Forest Version: 4.1.313
Client Log: https://gist.github.com/Miv2nir/6349e66053ba789606ae377be6600d7d
Crash report: https://gist.github.com/Miv2nir/031d0b381d77428f13219c07b5dfb5f9
Vivecraft Fabric Version: 0.0.13

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Miv2nir** [comment]
> This...this is a Fabric issue. This repository is for the Forge version of the mod, as evident by the Forge Version required by this issue ticket, not the Fabric Version.

Oh, I'm sorry, the fabric issue tracker says that if an issue is present on both fabric and forge versions it should go in forge tracker but oh well

**Comment by TropheusJ** [comment]
Can't be fixed by TF, Vivecraft issue: https://github.com/ferriarnus/VivecraftMod/issues/100

**Comment by TropheusJ** [comment]
supposedly fixed in February
