### ISSUE TITLE
Tool tier requirement block tags not working

### ISSUE THREAD

**Issue by Swedz** [TeamTwilight/twilightforest-fabric#159]
### Fabric Loader Version

Quilt 0.18.1-beta.30

### Fabric API Version

qfapi-4.0.0-beta.26 qsl-3.0.0-beta.25 fapi-0.72.0

### Twilight Forest Version

4.2.333

### Steps to Reproduce

Give a block the block tag `#twilightforest:needs_ironwood_tool`. Break the block with stone, iron, or something below ironwood tier. 

### What You Expected

The block should only allow ironwood tools and above to break the block.

### What Happened Instead

The block allows any tool to be used.

### Additional Details

Here's a screenshot of the block I have added the tag to (block tags are shown on the right) and you can see the one probe tooltip labels it as able to be mined with stone pickaxe. In practice it also allows it.
![2023-01-14_21 46 24](https://user-images.githubusercontent.com/6707125/212568949-194e4ce7-d110-4750-a42e-8304941e64c5.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
All of these should now be fixed:
- `needs_ironwood_tool`
- `needs_fiery_tool`
- `needs_steeleaf_tool`
- `needs_knightmetal_tool`
- `needs_giant_tool`
- `needs_ice_tool`
- `needs_glass_tool`
