### ISSUE TITLE
Server and client keeps crashing due to twilight forest?

### ISSUE THREAD

**Issue by Doseishy** [TeamTwilight/twilightforest-fabric#161]
### Fabric Loader Version

0.14.12

### Fabric API Version

0.72.0+1.19.2

### Twilight Forest Version

1.19.2-4.2.333

### Client Log

https://gist.github.com/Doseishy/fbb8cc835429f31e52bac564aaf1f95c

### Crash Report (if applicable)

https://gist.github.com/Doseishy/dc4c5da01ae9f4686498198f44241c5e

### Steps to Reproduce

I just updated twilight forest today. I also tried going back to the previous version and it still crashed for whatever reason now. 

### What You Expected

For the game and server to launch

### What Happened Instead

They keep crashing

### Additional Details

Not sure if the server log would be useful but here it is. https://gist.github.com/Doseishy/cc52319ceeffe901205f337f1f91e856
I did update other mods, however going back to the previous version of some of the updated mods seems to still cause a crash when twilight forest tries to load. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SeraphAngela** [comment]
Also had this issue, seemed to be caused by Porting Lib. Unsure if this affects all versions of Porting Lib, but I personally had problems with 2.1.705+1.19.2. Removing either mod fixed the problem.

**Comment by TropheusJ** [comment]
fixed [here](https://github.com/TeamTwilight/twilightforest-fabric/commit/ab8ee363c8b6cbca08565f79875bd3ae867500d7)
