### ISSUE TITLE
Twilight forest incompatible with the newest update of wilderwild 1.1.7 for 1.19.2 fabric 

### ISSUE THREAD

**Issue by LadySunx** [TeamTwilight/twilightforest-fabric#162]
### Fabric Loader Version

0.14.12

### Fabric API Version

0.72.0+1

### Twilight Forest Version

4.2.333

### Client Log

https://mclo.gs/vDdMFdD

### Crash Report (if applicable)

https://mclo.gs/FNCLNXn

### Steps to Reproduce

1. Update to wilder 1.1.7 for 1.19.2 fabric 
2. Load into the world and crash

### What You Expected

N/A

### What Happened Instead

N/A

### Additional Details

I did report this to the wilder wild github but they said it isn't caused by wilderwild but twilight forest, so they told me to report to y'all.

This crash only happens on the newest wilder wild update which is 1.1.7 but if you use 1.1.5 of wilder wild the twilight forest crash does not happen and you can load into the world fine. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [ ] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
corresponding issue: https://github.com/FrozenBlock/WilderWild/issues/198

**Comment by LadySunx** [comment]
Thank you for the help! I was about to report back to them but i see you already did thanks again.
