### ISSUE TITLE
Lots of bugs Fabric 1.19.2

### ISSUE THREAD

**Issue by MrJorman** [TeamTwilight/twilightforest-fabric#163]
### Fabric Loader Version

fabric-loader-0.14.12-1.19.2

### Fabric API Version

fabric-api-0.71.0+1.19.2.jar

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2

### Client Log

no log.

### Crash Report (if applicable)

no crash.

### Steps to Reproduce

1. Please change the texture of the iron staircase in the vanilla minecraft style, not in the 3D style, and it also has an x-ray visual bug.
2. The Ghast trophy has a broken model. Other trophies are also not visible in the hands. Fix the model.
3. The fire block also has a broken texture or the effect of its edges.
4. The quest ram banner is not displayed.
5. Spiral stone bricks have an x-ray effect
6. Banister's lose texture if you dock them with blocks (bug from old versions)
7. The staff of life absorption has a curved effect (not from the center) (player and other mobs)
![image](https://user-images.githubusercontent.com/55187962/213899769-340ff336-f39d-4ed9-b5da-54a8279fd55e.png)
![image](https://user-images.githubusercontent.com/55187962/213899788-6d3ad91d-c12e-4157-a4b8-5e432d588f0e.png)
![image](https://user-images.githubusercontent.com/55187962/213899790-a87a091d-34e1-491d-973e-dc45b5e53b65.png)
![image](https://user-images.githubusercontent.com/55187962/213899797-9b7d9f40-8b40-4597-82c8-832c5420df37.png)
![image](https://user-images.githubusercontent.com/55187962/213899808-180dcaa0-3c4e-4902-b938-fa230a4e2e49.png)
![image](https://user-images.githubusercontent.com/55187962/213899816-eaf3ac1d-c11c-4f5d-9fc2-790a072a9582.png)
![image](https://user-images.githubusercontent.com/55187962/213899836-2b6fa45e-3cd2-45f4-866e-7a2f82c0f763.png)
![image](https://user-images.githubusercontent.com/55187962/213899846-846a05c5-f1d3-4133-866c-5a0dcaefe1ea.png)
![image](https://user-images.githubusercontent.com/55187962/213899866-093dc56f-e4a5-4e84-a695-f6df4965bdb3.png)
![image](https://user-images.githubusercontent.com/55187962/213899878-79b74ac8-4d83-4d62-9597-627322d83c26.png)

### What You Expected

good game

### What Happened Instead

gg wp )

### Additional Details

i use Mods:

TwillightForest
Sodium
SodiumExtra
Lithium
CullLeveas
EntityCulling
MoreCulling
LazyDFY
FerriteCore
Indium
Debugify

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by MrJorman** [comment]
More Culling mod - add x-ray iron ladder

**Comment by GizmoTheMoonPig** [comment]
The iron ladder being 3d isnt a bug, this is an intended feature that isnt changing. 
4 is not a bug, he texture just isnt done yet. 
7 is also not a bug. The beam is supposed to shoot form the scepter itself, not from the player. 
Also please try to see if these are all issues without all your culling mods installed. Im pretty sure the banister visual bug is because of sodium, the others are likely caused by the MoreCulling.

**Comment by MrJorman** [comment]
> The iron ladder being 3d isnt a bug, this is an intended feature that isnt changing. 4 is not a bug, he texture just isnt done yet. 7 is also not a bug. The beam is supposed to shoot form the scepter itself, not from the player. Also please try to see if these are all issues without all your culling mods installed. Im pretty sure the banister visual bug is because of sodium, the others are likely caused by the MoreCulling.

7 bug.

**Comment by MrJorman** [comment]
You said it right, it should come from the player. Only for the sake of the test, use the scepter on zombies or spiders, and see where the particles come from, and then use it on the player, the particles will be displaced.

**Comment by MrJorman** [comment]
There is no bug with the fire block if the Sodium mod is not installed

**Comment by MrJorman** [comment]
Please change the texture of the stairs to another one, please. Take an example of a staircase from the Create mod, there is a very beautiful and vanilla texture of an andesite staircase, make it iron.

**Comment by GizmoTheMoonPig** [comment]
we're not going to do that. If you want it changed so bad you can make a resource pack to change it but we arent changing it in the base mod
