### ISSUE TITLE
Portal not working

### ISSUE THREAD

**Issue by Gabrienzo** [TeamTwilight/twilightforest-fabric#164]
### Fabric Loader Version

0.14.13

### Fabric API Version

0.69.0+1.19.2

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.301

### Steps to Reproduce

1. make the portal (3x3 or 2x2)
2. put the nature stuff
3. drop the diamond
4. where's portal?

### What You Expected

a portal

### What Happened Instead

nothing

### Additional Details

[mods pt1](https://prnt.sc/DVVrJUl-xdoe)
[mods pt2](https://prnt.sc/x1s9nBcwn36y)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
Update TF
