### ISSUE TITLE
Crashing while going to another dimentions with block and chains in inventory

### ISSUE THREAD

**Issue by ArtemDmitrievITMO** [TeamTwilight/twilightforest-fabric#170]
### Fabric Loader Version

fabric-loader-0.14.11-1.19.2

### Fabric API Version

Fabric-API-0.72.0-1.19.2

### Twilight Forest Version

4.2.333

### Crash Report (if applicable)

https://gist.github.com/ArtemDmitrievITMO/8be1d25f7e41b5f8d9a751e49209aa40#file-crash-2023-01-31_18-20-43-server-txt

### Steps to Reproduce

1)Put a block and chain in your inventory, build a portal (a bug appeared with both a portal to Nether and a portal to the twilight forest)
2)Go into portals several times. At the same time, you need to use a block and chain before teleportation, but not necessarily immediately before it
3)After several attempts, minecraft crashes at the "loading the world" stage, the same thing happens when you re-enter the world. If you delete the twilight forest, the world will load as it should

### What You Expected

I'm expecting the most ordinary teleportation with my favorite block and chain)

### What Happened Instead

minecraft crashes at the "loading the world" stage, the same thing happens when you re-enter the world. If you delete the twilight forest, the world will load as it should

### Additional Details

I have a large build that includes create, better Nether and Iris

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
I can't get this to happen, and looking at the code, there's multiple reasons this should be impossible. Maybe it was fixed already.
