### ISSUE TITLE
Crash with Create

### ISSUE THREAD

**Issue by papertek** [TeamTwilight/twilightforest-fabric#172]
### Fabric Loader Version

0.14.12

### Fabric API Version

0.73.2+1.19.2

### Twilight Forest Version

4.2.333

### Client Log

https://gist.github.com/papertek/80939cac73140d456b97e210cb922780

### Crash Report (if applicable)

https://gist.github.com/papertek/7ffc8abfbb29a32b2b7871beb89ff13b

### Steps to Reproduce

1. Install Create 0.5.0.i-925+1.19.2
2. Crash

### What You Expected

The game to run (to the main menu)

### What Happened Instead

The game did not run (crashed on launch)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by holmraven** [comment]
I think this occurs because create developers bumped porting-lib version, probably should be fixed by Twilight Forest Fabric devs updating porting-lib in a new release

**Comment by Lochbug** [comment]
You can temporarily fix this issue by using an older version of create.

**Comment by TygreWolf** [comment]
> You can temporarily fix this issue by using an older version of create.

An older version of Create may stop the twilight crash, but older versions of Create cause their own crashes, so I'd be swapping this problem for one I've already fixed by installing a new version of Create.  Failing forward is the better option here.  Good times.

**Comment by LordNoisy** [comment]
The version of porting-lib has been increased in the dev builds and for me it *seems* to be working, https://tamaized.com/azure/twilightforest/fabric/

**Comment by erindal** [comment]
> The version of porting-lib has been increased in the dev builds and for me it _seems_ to be working, https://tamaized.com/azure/twilightforest/fabric/

Thanks for this!

**Comment by AlphaMode** [comment]
Fixed in latest release
