### ISSUE TITLE
Aurora Castle Glacier Melting

### ISSUE THREAD

**Issue by AetheriMC** [TeamTwilight/twilightforest-fabric#174]
### Fabric Loader Version

0.14.13

### Fabric API Version

0.73.2+1.19.2

### Twilight Forest Version

1.19.2-4.2.333

### Client Log

https://gist.github.com/AetheriMC/3196bfb6a330b4233d7b0c52c8be3434

### Steps to Reproduce

1. Locate the Aurora Castle
2. Lo! The glacier, she melts!

### What You Expected

That the glacier surrounding the Aurora castle would stay frozen.

### What Happened Instead

This may be intended, so if that's the case I apologize in advance.

The glacier surrounding the Aurora castle, without entering the castle or defeating the queen, begins melting shortly after loading, which seems to be an unintended behavior.

### Additional Details

Please disregard the crash shown in the client log as it is not related to Twilight Forest.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
the ice should not melt unless there's light nearby. If this is still an issue, it's probably a mod incompat.

**Comment by Zarepheth** [comment]
I believe Fabric Seasons may cause the ice to melt - depending upon the current season and the biome settings for temperature and humidity. 

The modpack author may need to blacklist Twilight Forest dimension from the seasonal effects (assuming that mod has such capability). And if the mod does not, then it should be added.
