### ISSUE TITLE
[Suggestion] Add config option to disable dropped items traversing the portal

### ISSUE THREAD

**Issue by kbsmilk** [TeamTwilight/twilightforest-fabric#176]
### The Suggestion

Just an option to bypass item entities passing through the portal.

### Why Should It Be in the Mod?

I pinned down a transient tickrate problem on my server. Spark Profiler noted 31% of ticktime was spent on TF's changing dimensions for dropped items. (This was made worse by another mod, Very Many Players, I think. But this config would fix both issues)

Basically some dropped flowers fell in one player's portal. And I guess that since the portal lays on the ground, gravity was flinging the item entity through the portal constantly. Lag cleared up the instant that player removed the flowers.

Here is the profile: https://spark.lucko.me/qy6gXzUCSe?hl=24173,26379,96

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by TropheusJ** [comment]
features should be submitted to the forge repo.
