### ISSUE TITLE
[1.18.2] server crash

### ISSUE THREAD

**Issue by MSandro** [TeamTwilight/twilightforest-fabric#177]
### Fabric Loader Version

0.14.17

### Fabric API Version

0.75.1+1.18.2

### Twilight Forest Version

4.1.313

### Crash Report (if applicable)

https://gist.github.com/MSandro/8b47b63f2aef5e546a083e6b918ef688

### Steps to Reproduce

1. start the server
2. crash

### What You Expected

not crashing

### What Happened Instead

crash

### Additional Details

Modpack Sky Fabrication 3 v0.6.0 (not released yet)
https://github.com/MSandro/sky_fabrication3/tree/0.6.0

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
> AccessDeniedException: ./config/twilightforest-common.toml

fix your file permissions.
