### ISSUE TITLE
Uncrafting crash with Enderite

### ISSUE THREAD

**Issue by Dalethium** [TeamTwilight/twilightforest-fabric#183]
### Fabric Loader Version

0.14.17

### Fabric API Version

0.76.0+1.19.2

### Twilight Forest Version

4.2.335

### Client Log

N/A

### Crash Report (if applicable)

https://gist.github.com/Dalethium/dc9eea37457c4fa10cc2d9c478e8cef4

### Steps to Reproduce

1. Put diorite slabs in uncrafting table on dedicated server
2. Crash.

### What You Expected

Not to crash

### What Happened Instead

Crashed

### Additional Details

Seems to be an incompatibility, I've reported this to the enderite dev though I am unclear of if this is on your end or theirs to fix so I am reporting it here too.
https://github.com/Nic4Las/Minecraft-Enderite-Mod/issues/76

Please let me know if you need more info!

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
In the released version of Enderite for 1.19.2, the `fits` method in the `EnderiteShieldDecorationRecipe` is marked as client only, when it should not be.
This is not the case on github, so it should be fixed in a newer version of it.
This cannot be fixed by us.
