### ISSUE TITLE
Twilight Forest Incompatible with Dashloader causing it too crash. 

### ISSUE THREAD

**Issue by RDP8** [TeamTwilight/twilightforest-fabric#184]
Fabric Loader version: 0.14.18
Fabric API version: 0.76.0+1.19.2
Twilight Forest version: 4.2.335
Link to crash log: https://paste.gg/p/anonymous/bafb2da60e9941b6ad153beb83c45c46

Steps to reproduce:
1. Have Twilight forest and Dashloader installed. 

What I expected to happen: The game runs more stable and doesn't crash. 

What happened instead: Dashloader crashes due to Twilight forests incompatibility and then crashes the game.

**Comment by TropheusJ** [comment]
There's no crash in this log, and it's working fine for me. If it's still an issue, see if there's a crash log.
