### ISSUE TITLE
Crashes on start-up with latest Create Version 1.19.2

### ISSUE THREAD

**Issue by Poke097** [TeamTwilight/twilightforest-fabric#185]
### Fabric Loader Version

0.14.19

### Fabric API Version

fabric-api-0.76.0+1.19.2.jar

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.335

### Crash Report (if applicable)

https://gist.github.com/Poke097/03090a51beefc7cd30d008c4f7f8744a

### Steps to Reproduce

1. Install latest create and twilight forest
2. Start up
3. Crash

### What You Expected

To not crash, suspected because of porting lib, in stack trace

### What Happened Instead

I crashed on start up

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
fixed in latest Create
