### ISSUE TITLE
Exception in server tick loop: Shift-click armor server crash

### ISSUE THREAD

**Issue by SmallSansSerif** [TeamTwilight/twilightforest-fabric#186]
### Fabric Loader Version

0.14.19

### Fabric API Version

fabric-api-0.76.0+1.19.2

### Twilight Forest Version

twilightforest-fabric-1.19.2-4.2.335

### Crash Report (if applicable)

https://gist.github.com/SmallSansSerif/7326344487dd4a13f6399cf7eb89e09e

### Steps to Reproduce

1. Shift click TF Phantom armor chest plate to equip.
2. Server hard crashes immediately with Exception in server tick loop. See server crash report.

### What You Expected

Server to remain stable when user shift-clicks armor to equip.

### What Happened Instead

TF crashed the server after user shift-clicked a Phantom TF armor into a slot.

### Additional Details

Might be similar or not to another mod armor shift click problem we were having in same pack here. The mod was updated with fix, second link below.

https://github.com/chronosacaria/MCStoryModeArmors/issues/9
https://github.com/chronosacaria/MCStoryModeArmors/commit/b6753d8325245b82891475eca485b92aafbe3ae5

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by BlitzProGaming** [comment]
Hello,

I am also having this issue. Shift-clicking any armor results in a crash with a similar crash log.

Fabric 0.14.17
Fabric API - 0.76.0+1.19.2

---- Minecraft Crash Report ----
// Sorry :(

Time: 2023-04-18 23:31:13
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class twilightforest.enums.TwilightArmorMaterial does not define or inherit an implementation of the resolved method 'abstract java.lang.String method_7694()' of interface net.minecraft.class_1741.
	at dev.emi.trinkets.SurvivalTrinketSlot.handler$cmk000$levelz$canInsertMixin(SurvivalTrinketSlot.java:550)
	at dev.emi.trinkets.SurvivalTrinketSlot.method_7680(SurvivalTrinketSlot.java)
	at net.minecraft.class_1723.md49c311$trinkets$lambda$transferSlot$4$0(class_1723.java:2248)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at net.minecraft.class_1723.handler$ekl000$trinkets$transferSlot(class_1723.java:2245)
	at net.minecraft.class_1723.method_7601(class_1723.java)
	at net.minecraft.class_1703.method_30010(class_1703.java:394)
	at net.minecraft.class_1703.method_7593(class_1703.java:293)
	at net.minecraft.class_3244.method_12076(class_3244.java:1770)
	at net.minecraft.class_2813.method_12191(class_2813.java:58)
	at net.minecraft.class_2813.method_11054(class_2813.java:13)
	at net.minecraft.class_2600.method_11072(class_2600.java:22)
	at net.minecraft.class_3738.run(class_3738.java:18)
	at net.minecraft.class_1255.method_18859(class_1255.java:157)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776)
	at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159)
	at net.minecraft.class_1255.method_16075(class_1255.java:131)
	at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758)
	at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752)
	at net.minecraft.class_1255.method_18857(class_1255.java:140)
	at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.base/java.lang.Thread.run(Thread.java:833)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Linux (amd64) version 5.15.0-67-generic
	Java Version: 17.0.6, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 3914210304 bytes (3732 MiB) / 14310965248 bytes (13648 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 4
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 9 5900X 12-Core Processor
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): -0.00
	Number of physical packages: 1
	Number of physical CPUs: 12
	Number of logical CPUs: 24
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 81780.02
	Virtual memory used (MB): 74438.84
	Swap memory total (MB): 17407.99
	Swap memory used (MB): 457.44
	JVM Flags: 3 total; -XX:ActiveProcessorCount=4 -Xmx16384M -Xms10649M
	Fabric Mods: 
		additionaladditions: Additional Additions 5.1.0
		additionalbanners: AdditionalBanners 10.1.7
		additionalstructures: Additional Structures 4.1.1
		adorn: Adorn 3.8.2+1.19.2
		advanced_runtime_resource_pack: Runtime Resource Pack 0.6.4
		adventurez: AdventureZ 1.4.17
		angling: Angling Mod 1.0.0
		another_furniture: Another Furniture 2.1.2-1.19.2
		arcanus: Arcanus 1.30
		architectury: Architectury 6.5.77
		backslot: BackSlot 1.2.11
		backslotaddon: BackSlot Addon 1.0.10
		balm-fabric: Balm 4.5.7
		beautify: Beautify 1.1.0+fabric-1.19.2
		bedbenefits: BedBenefits 9.1.2
		beekeeperhut: Friends&Foes - Beekeeper Hut 1.2.0
		betterbeacon: Better Beacons 1.0.8
		betterdeserttemples: YUNG's Better Desert Temples 1.19.2-Fabric-2.2.1
		betterdungeons: YUNG's Better Dungeons 1.19.2-Fabric-3.2.1
		betterfortresses: YUNG's Better Nether Fortresses 1.19.2-Fabric-1.0.5
			org_reflections_reflections: reflections 0.10.2
		bettermineshafts: YUNG's Better Mineshafts 1.19.2-Fabric-3.2.0
		betteroceanmonuments: YUNG's Better Ocean Monuments 1.19.2-Fabric-2.1.0
		betterstrongholds: YUNG's Better Strongholds 1.19.2-Fabric-3.2.0
		bettervillage: Better village 2.0.0
		betterwitchhuts: YUNG's Better Witch Huts 1.19.2-Fabric-2.1.0
		biomemakeover: Biome Makeover 1.19.2-1.6.4
		boatcontainer: BoatContainer 1.2.4
		bookshelf: Bookshelf 16.2.18
		bountiful: Bountiful 3.0.0
		capybara: Capybara 2.0.1
		carryon: Carry On 2.0.4.6
		charm: Charm 4.4.4
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
		chefsdelight: Chef's Delight 1.0.2-fabric-1.19.2
			structurized-reborn: Structurized Reborn 1.19-01
		chimes: Chimes 1.1.4
		chipped: Chipped 2.1.4
		chunky: Chunky 1.3.38
		chunkyborder: Chunkyborder 1.1.34
		cloth-api: Cloth API 4.0.65
			cloth-basic-math: cloth-basic-math 0.6.1
			cloth-client-events-v0: Cloth Client Events v0 4.0.65
			cloth-common-events-v1: Cloth Common Events v1 4.0.65
			cloth-utils-v1: Cloth Utils v1 4.0.65
		cloth-config: Cloth Config v8 8.2.88
		configured: Configured 2.0.0
		convenientdecor: Convenient Decor 0.1.0
		cookingforblockheads: Cooking for Blockheads 13.3.1
		creativecore: CreativeCore (Fabric) 2.9.3
		crittersandcompanions: Critters and Companions 1.19.2-1.0.3
		croptopia: Croptopia 2.2.2
			com_typesafe_config: config 1.4.1
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		culturaldelights: Cultural Delights Fabric 0.14.9+1.19.2
			terraform-wood-api-v1: Terraform Wood API (v1) 4.2.0
		darkmining: DarkMining - Better Block Drops 1.0.3
		darkpaintings: DarkPaintings 13.1.5
		darkquesting: DarkQuesting - A Quest Mod 1.1.0
		debugify: Debugify 2.8.0
		decor4fabric: Decor4Fabric 1.2.1
		decorative_blocks: Decorative Blocks 3.0.0
		deepslatecutting: Deepslate Cutting 1.5.0
			maybe-data: Maybe data 1.3.2-1.19.2
		discholder: Kenza's Disc Holder and DJ 2.0.0
		disguiselib: Disguise Library 1.3.2
		do_a_barrel_roll: Do a Barrel Roll 2.6.2+1.19.2
			cardinal-components-base: Cardinal Components API (base) 5.0.2
			cardinal-components-entity: Cardinal Components API (entities) 5.0.2
			cicada: CICADA 0.1.2
				langfiles-plus: Langfiles Plus 1.0.0
		dramaticdoors: Dramatic Doors (Fabric) 1.19.2-1.4.2
		dummmmmmy: MmmMmmMmmMmm 1.19.2-1.7.1
		dynmap: Dynmap 3.4
		ecologics: Ecologics 2.1.11
		eer: Erroring Entity Remover 1.0.3+1.19
		essential_commands: Essential Commands 0.30.0-mc1.19.2
			ec-core: Essential Commands Core 1.3.0-mc1.19.2
			org_yaml_snakeyaml: snakeyaml 1.33
			playerabilitylib: Pal 1.6.0
		exlinefurniture: Exline's Furniture 2.3.2
		expandeddelight: Expanded Delight 0.2.5.2
		extraalchemy: Extra Alchemy 1.9.0
		fabric-api: Fabric API 0.76.0+1.19.2
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.1+16f1e31390
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.2+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.3.0+4bc6e26290
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.8+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.36+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.6+b7d1888890
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.39+9244241690
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.13+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.16+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.24+33fbc73890
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.2+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.4+edbdcddb90
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabric-language-kotlin: Fabric Language Kotlin 1.9.3+kotlin.1.8.20
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.8.20
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.8.20
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.20.1
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.5.0
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.5.0
		fabricloader: Fabric Loader 0.14.17
		fabsit: FabSit 1.5.3+1.19
		farmersdelight: Farmer's Delight 1.19.2-1.3.9
		farmersrespite: Farmer's Respite 2.2.4
		farmingforblockheads: Farming for Blockheads 11.2.0
		fdjei: Just Enough Farmer's Recipes 1.0.1
		ferritecore: FerriteCore 5.0.3
		floralench: Floral Enchantment Fabric-1.19.2-1.1.2
		flowerymooblooms: Friends&Foes - Flowery Mooblooms 1.0.0
		forgeconfigapiport: Forge Config API Port 4.2.11
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
		friendsandfoes: Friends&Foes 1.6.8
		geckolib3: Geckolib 3.1.40
			com_eliotlash_mclib_mclib: mclib 20
		geodes: More Geodes 1.6.4+1.19
		glowingbanners: Glow Banners 1.2.0
		goated: You've Goat to be kidding me 1.19.2-1.3.1
		goblintraders: Goblin Traders 1.8.1
		graveyard: The Graveyard 2.3
		graveyard_biomes: The Graveyard Biomes 1.6
			omega-config: OmegaConfig 1.2.2-1.18.1
		guardvillagers: Guard Villagers Fabric 1.19.2-1.1.2
		iceberg: Iceberg 1.0.46
		immersive_aircraft: Immersive Aircraft 0.4.2+1.19.2
		immersive_armors: Immersive Armors 1.5.5+1.19.2
		immersive_paintings: Immersive Paintings 0.6.0+1.19.2
		incendium: Incendium 5.1.4
		jamlib: JamLib 0.6.0+1.19
		java: OpenJDK 64-Bit Server VM 17
		jei: Just Enough Items 11.6.0.1011
		jeresources: Just Enough Resources 1.2.2.200
		kambrik: Kambrik 4.0-1.19.2
		kaupens_paintings: Kaupenjoe's Translated Pompous Paintings 1.1-1.19.2
		lazydfu: LazyDFU 0.1.3
		ledger: Ledger 1.2.5
		levelz: LevelZ 1.4.7
			libgui: LibGui 6.0.1+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		libraryferret: Library ferret 3.0.0
		libz: LibZ 1.0.0
		lithium: Lithium 0.10.4
		lovely_snails: Lovely Snails 1.1.0+1.19
		luckperms: LuckPerms 5.4.46
		mageflame: Mage Flame v1.4.0
		marketcrates: Marketcrates 1.5
		mavapi: More Axolotl Variants API 1.0.1
		mavm: More Axolotl Variants Mod 1.2.0
		mcwbridges: Macaw's Bridges 2.0.7
		mcwdoors: Macaw's Doors 1.0.8
		mcwfences: Macaw's Fences and Walls 1.0.7
		mcwlights: Macaw's Lights and Lamps 1.0.5
		mcwpaintings: Macaw's Paintings 1.0.4
		mcwpaths: Macaw's Paths and Pavings 1.0.2
		mcwroofs: Macaw's Roofs 2.2.3
		mcwtrpdoors: Macaw's Trapdoors 1.0.9
		mcwwindows: Macaw's Windows 2.1.2
		medieval_deco: PlayTics Deco 1.0
		medievalweapons: Medieval Weapons 1.4.4
			reach-entity-attributes: Reach Entity Attributes 2.3.0
		memoryleakfix: Memory Leak Fix 1.0.0
			com_github_llamalad7_mixinextras: MixinExtras 0.2.0-beta.6
		midnightlib: MidnightLib 1.0.0
		minecraft: Minecraft 1.19.2
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		mixintrace: MixinTrace 1.1.1+1.17
		moonlight: Moonlight 1.19.2-2.2.29
		morebannerfeatures: More Banner Features 1.1.3
		morebannerlayers: More Banner Layers 1.0.0-1.19
		motleysmusicdiscs: Motley's Music Discs 0.0.1-1.19
		music_dog: Mdisc_dog 1.0
		mythicmounts: Mythic Mounts 1.19.2-7.1
		naturalist: Naturalist 2.1.1
		netherdepthsupgrade: Nether Depths Upgrade fabric-2.0.4-1.19.2
		nethersdelight: Nether's Delight 1.0.1
		nochatreports: No Chat Reports 1.19.2-v1.13.12
		npcvariety: NPC Variety 2.2.2
		openblocks: Open Block Elevator Mod 0.0.2-1.19.X
		owo: oωo 0.9.3+1.19
			blue_endless_jankson: jankson 1.2.1
		pack_it_up: Pack It Up! 0.3.0+1.19
		paintings: Paintings++ 10.2.4.0
		patchouli: Patchouli 1.19.2-77-FABRIC
			fiber: fiber 0.23.0-2
		pfm: Paladin's Furniture 1.1.1
		polymer-all: Polymer (Packed) 0.2.25+1.19.2
			polymer: Polymer (Core) 0.2.25+1.19.2
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.3+1.19.2
			polymer-autohost: Polymer Auto Host 0.1.4+1.19.2
			polymer-blocks-ext: Polymer Blocks 0.1.0-alpha.9+1.19.2
		polymorph: Polymorph 0.46.1+1.19.2
			cardinal-components-item: Cardinal Components API (items) 5.0.1
			spectrelib: SpectreLib 0.11.0+1.19
		puzzleslib: Puzzles Lib 4.3.12
			cardinal-components-block: Cardinal Components API (blocks) 5.0.2
			cardinal-components-chunk: Cardinal Components API (chunks) 5.0.2
			cardinal-components-world: Cardinal Components API (worlds) 5.0.2
		rare-ice: Rare Ice 0.5.0
		redmorestructure: Reds More Structures 1.0.4-1.19.2
		renameit: RenameIt 1.4.0+1.19.x
			fabric-api-base: Fabric API Base 0.4.20+afca2f3e85
			fabric-permissions-api-v0: fabric-permissions-api 0.2-SNAPSHOT
			placeholder-api: Placeholder API 2.0.0-pre.2+1.19.3
			server_translations_api: Server Translations API 1.4.19+1.19.3
		resourcefullib: Resourceful Lib 1.1.22
		rightclickharvest: Right Click Harvest 3.1.0+1.19-1.19.2
		runelic: Runelic 14.1.4
		skinned_lanterns: Skinned Lanterns 2.0.0
		smallships: Small Ships 2.0.0a1.1.1
		spelunker: Spelunker 1.5.2-mc1.19
			tweed4_data: tweed4_data 1.2.1
		starlight: Starlight 1.1.1+fabric.ae22326
		strawgolem: Straw Golem 2.0.0-beta.5
		strawstatues: Straw Statues 4.0.10
		structory_towers: Structory: Towers 1.0.0
		supplementaries: Supplementaries 1.19.2-2.3.2
		taterzens: Taterzens 1.11.1
			config2brigadier: Config to Brigadier 1.2.1
		taxfreelevels: Tax Free Levels 1.3.3
		terrablender: TerraBlender 2.0.1.136
		terralith: Terralith 2.3
		theimpossiblelibrary: The Impossible Library 1.19.2-fabric-0.2.4
		tradernpcs: Trader NPCs 1.2.0
		transparent: Transparent 5.1.2
		trinkets: Trinkets 3.4.2
		twilightforest: The Twilight Forest 4.2.335
			com_google_code_findbugs_jsr305: jsr305 3.0.2
			javax_annotation_javax_annotation-api: javax.annotation-api 1.3.2
			mm: Manningham Mills 2.3
			porting_lib: Porting Lib 2.1.727+1.19.2
				forge_tags: Porting Lib Tags 3.0
				porting_lib_accessors: Porting Lib Accessors 2.1.727+1.19.2
				porting_lib_attributes: Porting Lib Attributes 2.1.727+1.19.2
				porting_lib_base: Porting Lib Base 2.1.727+1.19.2
				porting_lib_common: Porting Lib Common 2.1.727+1.19.2
				porting_lib_constants: Porting Lib Constants 2.1.727+1.19.2
				porting_lib_entity: Porting Lib Entity 2.1.727+1.19.2
				porting_lib_extensions: Porting Lib Extensions 2.1.727+1.19.2
				porting_lib_fake_players: Porting Lib Fake Players 2.1.727+1.19.2
				porting_lib_lazy_registration: Porting Lib Lazy Register 2.1.727+1.19.2
				porting_lib_model_generators: Porting Lib Model Generators 2.1.727+1.19.2
				porting_lib_model_loader: Porting Lib Model Loader 2.1.727+1.19.2
				porting_lib_models: Porting Lib Models 2.1.727+1.19.2
				porting_lib_networking: Porting Lib Networking 2.1.727+1.19.2
				porting_lib_obj_loader: Porting Lib Obj Loader 2.1.727+1.19.2
				porting_lib_transfer: Porting Lib Transfer 2.1.727+1.19.2
				serialization_hooks: Serialization Hooks 0.3.26
		universal-graves: Universal Graves 2.1.3+1.19.2
			common-protection-api: Common Protection API 1.0.0
			hologram-api: Hologram API 0.2.2+1.19
			sgui: sgui 1.1.5+1.19.1
		villager-hats: Villager Hats 1.4.3
		villagernames: Villager Names 4.2.1
			cardinal-components-level: Cardinal Components API (world saves) 5.0.2
		villagersplus: Villagers Plus 1.9
		voicechat: Simple Voice Chat 1.19.2-2.4.4
		wabi_sabi_structures: Wabi-Sabi Structures 1.1.2
		wandering_collector: Wandering Collector 1.1.3+mc1.19
			tweed4_annotated: tweed4_annotated 1.3.1+mc22w17a
			tweed4_base: tweed4_base 1.6.0+mc22w17a
			tweed4_data_hjson: tweed4_data_hjson 1.1.1+mc22w17a
		wandering_trapper: Wandering Trapper 2.0.0
		wetlands: Beneath the Wetlands 1.0.2
		wilderwild: Wilder Wild 1.1.13-Fabric+1.19.2
			caffeineconfig: CaffeineConfig 1.0.0+1.17
			frozenlib: FrozenLib 1.1.13-Fabric+1.19.2
			nbtcrafting: NBT Crafting 2.2.3+mc1.19
		witchmobility: Witch Mobility Mod 1.3.1-1.19.2
		wondrouswilds: Wondrous Wilds 1.19.2-1.1.6
		worldedit: WorldEdit 7.2.12+6240-87f4ae1
		yet-another-config-lib: YetAnotherConfigLib 2.2.0-for-1.19.2
		yosbr: YOSBR 0.1.1
		yungsapi: YUNG's API 1.19.2-Fabric-3.8.8
			org_javassist_javassist: javassist 3.28.0-GA
		yungsbridges: YUNG's Bridges 1.19.2-Fabric-3.1.0
		yungsextras: YUNG's Extras 1.19.2-Fabric-3.1.0
	Server Running: true
	Player Count: 4 / 69; [class_3222['M3AP_'/477310, l='ServerLevel[Breadwars2023]', x=1990.08, y=-37.00, z=808.82], class_3222['W_o_m_a_n'/479461, l='ServerLevel[Breadwars2023]', x=1982.22, y=93.00, z=788.12], class_3222['MilkThenCereal'/532595, l='ServerLevel[Breadwars2023]', x=321.69, y=99.84, z=745.48], class_3222['GraceMotley'/571077, l='ServerLevel[Breadwars2023]', x=309.74, y=100.49, z=746.52]]
	Data Packs: vanilla, Fabric Mods, Goated Generated Pack, Supplementaries Generated Pack, file/Repurposed_Structures-Chef's_Delight_v1.zip, file/armor statues v2.8.4.zip, file/coordinates hud v1.2.3.zip, file/custom nether portals v2.3.6.zip
	World Generation: Stable
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)

**Comment by TropheusJ** [comment]
fixed in latest commits to 1.18 and 1.19
