### ISSUE TITLE
Crash on server with netty pipeline error and not even in twilight forest

### ISSUE THREAD

**Issue by kristinjkristin** [TeamTwilight/twilightforest-fabric#191]
### Fabric Loader Version

0.14.17

### Fabric API Version

fabric-api-0.75.1+1.19.2

### Twilight Forest Version

 twilightforest-fabric-1.19.2-4.2.335.jar

### Client Log

<script src="https://gist.github.com/kristinjkristin/412601ab3fdae056086f6fcfd4ac8012.js"></script>

### Crash Report (if applicable)

<script src="https://gist.github.com/kristinjkristin/be98c5b8259334b0d2487f9ea3a5d7dd.js"></script>

### Steps to Reproduce

1. Occurs shortly after logging on
2. no one in twilight forest
3. happen a lot when pocket wormhole is used for teleporting
4. items missing or duplicated in inventory
5. nothing has been added or removed from client side or server side mods

### What You Expected

I've been playing on the server without issue for over 2 months, only happened the last two days and it isn't happening to anyone else.

### What Happened Instead

02.05 00:08:37 [Server] Netty Epoll Server IO #0/ERROR Exception occurred in netty pipeline
02.05 00:08:37 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
02.05 00:08:37 [Server] Netty Epoll Server IO #0/ERROR Twilight Forest: Exception occurred in netty pipeline
02.05 00:08:37 [Server] INFO io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer

This error appears in the server console everytime i crash. 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
The server error is TF printing an error that is normally hidden. It's there twice because you have another mod doing the same thing.
That is not a TF issue, or even an error at all. That message basically just means the client disconnected from the server.

For the actual crash on your client, there's 3 mods involved: Charm, Paradise Lost, and Tom's Storage.
The error is triggered by Paradise Lost, but one of the other two may have caused it indirectly.

**Comment by 630R63** [comment]
I wish I knew how to stop this console spam:

![image](https://github.com/TeamTwilight/twilightforest-fabric/assets/6078866/34a66a39-e853-4bdd-99f1-ca29bab9a988)
