### ISSUE TITLE
Incompatibility with Create mod 0.5.0g -796 

### ISSUE THREAD

**Issue by skeeterj2003** [TeamTwilight/twilightforest-fabric#194]
Fabric Loader version:
Fabric API version:
Twilight Forest version: 
Link to crash log: 

Steps to reproduce:
1. Install create 0.5.0 -796
2. Install Twilight forest 4.2.357

What I expected to happen:
Looking at a fluid tank from the create mod while wearing the create goggles, the player should be able to see how much fluid is in the tank as a GUI on the player's screen

What happened instead:
Game immediately crashes instead of displaying GUI

**Comment by TropheusJ** [comment]
try with a newer version of Create
