### ISSUE TITLE
Slide traps are invisible while moving

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#2]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38

Steps to reproduce:
1. Place a slide trap block
2. Wait for it to move

What I expected to happen:
The slide trap would not turn invisible while moving.

What happened instead:
The slide trap vanishes, makes whirly wooden sounds for a bit, and then appears in a different location. I presume that it's supposed to be visibly moving while this happens.

**Comment by Dragon-Seeker** [comment]
There currently a WIP block so it seems. It will be fixed later.
