### ISSUE TITLE
The uncrafting table crafting

### ISSUE THREAD

**Issue by CosmicEntertain** [TeamTwilight/twilightforest-fabric#201]
### Fabric Loader Version

1.19.2

### Fabric API Version

1.19.2

### Twilight Forest Version

4.2.357

### Steps to Reproduce

Just trying to craft it in all of fabric 6.

### What You Expected

A uncrafting table.

### What Happened Instead

Didn't pop up as a craft and it doesn't have a recipe.

### Additional Details

Is there a mod that isn't allowing me to craft the table?
or can people reenable the crafting recipe?
![image_2023-07-03_182429587](https://github.com/TeamTwilight/twilightforest-fabric/assets/116524385/7c9fd424-fd9c-41dd-aa03-0477c22ed64f)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Tamaized** [comment]
The modpack probably disabled it

**Comment by CosmicEntertain** [comment]
> The modpack probably disabled it

is there a way to try and fix it?

**Comment by GizmoTheMoonPig** [comment]
AoF attempts to completely erase the table from the game because theyre too lazy to configure it themselves. youll have to talk to them about how to reenable it. I assume its a couple kubejs scripts disabling it
