### ISSUE TITLE
[Netty Client IO #0/ERROR]: Twilight Forest: Exception occurred in netty pipeline

### ISSUE THREAD

**Issue by FatalityWar** [TeamTwilight/twilightforest-fabric#202]
### Fabric Loader Version

0.14.21

### Fabric API Version

0.76.0

### Twilight Forest Version

4.2.357

### Client Log

https://gist.github.com/FatalityWar/30673fd75a4e87d1508745a8a808f166

### Steps to Reproduce

1. Step Logged in to the server via lan.
2. Disconnected immediately.
3. Error: java.io.IOException: An established connection was aborted by the software on the host machine.
4. Test performed as host, obtained the error.
5. Test performed on another computer, with the same modpack list, obtained the same error.

### What You Expected

Server should enter the screen of selection of race and class in the menu of Origins.

### What Happened Instead

Give a quick flash of the origins mod menu and then get the error, and back to the minecraft home menu.
ERRO: java.io.IOException: An established connection was aborted by the software on the host machine.

### Additional Details

I think it's related to the mods of LevelZ and Jobz, which are related about players and server.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by gildervine** [comment]
same issue here, what helped for me was to disable the ipv6 protocol in the network settings, only running ip4 kept me from getting disconnected

**Comment by TropheusJ** [comment]
That error is just TF printing an error that's normally hidden, useful for debugging. It will be removed in the next update.
The actual issues is extremely unlikely to be related to TF.
