### ISSUE TITLE
1.20.1 versiyon update

### ISSUE THREAD

**Issue by Rogenar** [TeamTwilight/twilightforest-fabric#204]
### The Suggestion

You haven't updated your mod for other versions after version 1.19.2. When do you plan to update to higher versions?

### Why Should It Be in the Mod?

For players playing on the latest versions.

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
This isnt what the issue tracker is for. The port will happen when our fabric team gets to it.

**Comment by antonio464** [comment]
polskaAAAAAAAAAAA
