### ISSUE TITLE
[Suggestion] Make a 1.20.1 version of the Fabric Mod

### ISSUE THREAD

**Issue by enderpirate98** [TeamTwilight/twilightforest-fabric#210]
### The Suggestion

On your guy's Curseforge page you do seem to have fabric builds which is great but the problem is that there have been no updates to them for 5 months, you guys have seem to update your forge version a lot with the latest being from a week ago but why no fabric? What is wrong with Fabric releases? You seem to have time for forge.

### Why Should It Be in the Mod?

There are tons and tons of modpacks out there that have 1.20.1 versions but it would be nice if the fabric versions could also have this wonderful mod! Thanks for listening!

### Please Read and Confirm the Following

- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by Drullkus** [comment]
It'll happen when it happens

**Comment by EfficientStinkbug** [comment]
Still on 1.19 only :(
