### ISSUE TITLE
[1.18.2] uncrafting table crash with enderite mod

### ISSUE THREAD

**Issue by PikachuGabe** [TeamTwilight/twilightforest-fabric#214]
### Fabric Loader Version

0.14.24

### Fabric API Version

0.76.0+1.18.2

### Twilight Forest Version

4.1.313

### Client Log

https://gist.github.com/PikachuGabe/00771a1e1baaa1fdc16e7f027abd7f76

### Crash Report (if applicable)

https://gist.github.com/PikachuGabe/916f5888bbbe1bccffa61a14f3f50eb8

### Steps to Reproduce

1. download both enderite mod and twilight forest fabric
2. (only on a server) try to place and use an uncrafting table on any item
3. watch as the server goes up in flames

### What You Expected

the server to not crash and the uncrafting table to work

### What Happened Instead

the server crashed and the item didnt even get uncrafted

### Additional Details

similar to #183 but with a different responsible file and error. enderite mod version is 1.3.5-1.18.2, issue was discovered by accident while looking for the crash with #183 that i suspected was happening on a server i play on, and was trying to make a modified jar to fix. issue was reproduced on a computer-hosted fabric server with performance mods, fabric-server-mc.1.18.2-loader.0.14.24-launcher.0.11.2.jar is the server jar. an uncrafting table crash (#183 again) is reported to the enderite team with no comment yet.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
This is an issue with Enderite (same issue as the ticket you linked) and is not fixable on TF's end. Issue is this line here which shouldnt exist: https://github.com/Nic4Las/Minecraft-Enderite-Mod/blob/Fabric-1.18.2/src/main/java/net/enderitemc/enderitemod/misc/EnderiteElytraSpecialRecipe.java#L89
I highly doubt theyre gonna fix it themselves but nothing can be done by us

**Comment by PikachuGabe** [comment]
I had reported it here to seek assistance, since #183 was reported to enderite at the same time with still no response(hence they likely dont respond), and while i understand this was missuse of bug reports, it atleast allows me to fix it and try to make a pull request so they fix it.
