### ISSUE TITLE
[Suggestion] porting lib

### ISSUE THREAD

**Issue by espresso3** [TeamTwilight/twilightforest-fabric#215]
### The Suggestion

Hi,

I have did in 1.19.2 and 1.19.4, but don't work. Then I take see in the logs that ''porting lib'' sit and that mod can I not lauch. Super rare, but is true. That mod I have did early and then fail that mod.
Very rare that I can alone see in the log by twilight forest.
Mabye if that fix more then do work. Or try without porting lib and make the portals with a datapack portal/dimension. Or question by ''betterend'' (bclib) or ''minecells or deeper and darker'' how make him portal.
Porting lib have some issue, but how? I don't know. 
I wish to you a super fine day

### Why Should It Be in the Mod?

portinglib have a issue by players, but which, I don't.

### Please Read and Confirm the Following

- [ ] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by GizmoTheMoonPig** [comment]
Porting lib is a library mod that contains various events and hooks that fabric doesn't have, I don't think it actually has anything to do with portals. The library is required for the mod as base TF uses a TON of systems from forge. The library is used in a bunch of other ported forge mods, such as create. 
Do note the 1.19.4 version of fabric is not usable, hence why there isn't a build on curseforge. The 1.19.2 one doesn't worn on the newest fabric api, you'll need to downgrade it. I'm not sure which version it needs to go down to, it just needs to be lower than latest.
