### ISSUE TITLE
All armour renders as missing texture

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#24]
### Fabric Loader Version

0.12.5

### Fabric API Version

0.42.1

### Cloth Config Version

5.1.40

### Twilight Forest Version

4.0.133

### Steps to Reproduce

1. Put on any TF armour piece

### What You Expected

Armour would look normal

### What Happened Instead

Armour appears as black and purple squares

### Additional Details

![2021-11-11_20 23 43](https://user-images.githubusercontent.com/69029346/141409660-b263e77e-e90b-4fa2-bdc7-0ecf7bd56729.png)
![2021-11-11_20 23 50](https://user-images.githubusercontent.com/69029346/141409663-310f7522-c8ba-4ee0-8aa8-b3b5b0a73c64.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
What other mods are you using?

**Comment by saltyseadoggo** [comment]
[Alloy Forgery](https://www.curseforge.com/minecraft/mc-mods/alloy-forgery) 2.0.6
[Ametherience](https://www.curseforge.com/minecraft/mc-mods/ametherience) 1.0.0
[Appleskin](https://www.curseforge.com/minecraft/mc-mods/appleskin) 2.1.3
[Architectury](https://www.curseforge.com/minecraft/mc-mods/architectury-fabric) 2.6.35
[Axolotl Item Fix](https://www.curseforge.com/minecraft/mc-mods/axolotl-bucket-fix) 1.1.3
[BedrockWaters](https://www.curseforge.com/minecraft/mc-mods/bedrockwaters) 1.5.0
[Charm](https://www.curseforge.com/minecraft/mc-mods/charm) 3.3.2
[Clear Hitboxes](https://www.curseforge.com/minecraft/mc-mods/clear-hitboxes) 1.12
[Desolation](https://www.curseforge.com/minecraft/mc-mods/desolation) 1.1.5
[Dispenser Cauldron](https://www.curseforge.com/minecraft/mc-mods/fabric-dispenser-cauldron) 1.0.4
[Enhanced Block Entities](https://www.curseforge.com/minecraft/mc-mods/enhanced-block-entities) 0.5
[Carpet](https://www.curseforge.com/minecraft/mc-mods/carpet) 1.4.51+v211
[Farmer's Delight](https://www.curseforge.com/minecraft/mc-mods/farmers-delight-fabric) 0.1.2
[GeckoLib](https://www.curseforge.com/minecraft/mc-mods/geckolib-fabric) 3.0.19
[Iris and Sodium](https://www.curseforge.com/minecraft/mc-mods/irisshaders) 1.1.2+build.9
[Item Model Fix](https://www.curseforge.com/minecraft/mc-mods/item-model-fix) 1.0.2
[Malilib](https://www.curseforge.com/minecraft/mc-mods/malilib) 0.10.0-dev.26
[Minihud](https://www.curseforge.com/minecraft/mc-mods/minihud) 0.19.0-dev.20210707.150016
[Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) 2.0.14
[Mythic Metals](https://www.curseforge.com/minecraft/mc-mods/mythicmetals) 0.10.1
[owolib](https://www.curseforge.com/minecraft/mc-mods/owo-lib) 0.3.1
[Recipe Reshaper](https://www.curseforge.com/minecraft/mc-mods/recipe-reshaper) 0.1-b
[Roughly Enough Items](https://www.curseforge.com/minecraft/mc-mods/roughly-enough-items) 6.0.307-alpha
[Shulker Box Tooltip](https://www.curseforge.com/minecraft/mc-mods/shulkerboxtooltip) 3.0.3
[Twigs](https://www.curseforge.com/minecraft/mc-mods/twigs) 1.0.2
[WTHIT](https://www.curseforge.com/minecraft/mc-mods/wthit) 3.10.0

**Comment by saltyseadoggo** [comment]
Confirmed to happen without any other mods, only TF, Fabric API and cloth config, on loader 12.5.

**Comment by Dragon-Seeker** [comment]
Hmmmm, well that is not good as the previous implementation worked, well Ill see about diagnosing such sometime soon
