### ISSUE TITLE
Many recipes went missing that were working before

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#26]
### Fabric Loader Version

0.12.5

### Fabric API Version

0.42.1

### Cloth Config Version

5.1.40

### Twilight Forest Version

4.0.133

### Steps to Reproduce

Use REI to look up **recipes** for the following:
- Maze Map
- Maze/Ore Map
- Magic Map
- Magic Map Focus
- Raw Ironwood
- Carminite
- All TF banner patterns
- Block of Ironwood
- Block of Steeleaf
- Block of Fiery Metal
- All TF chests
- All bannisters
- Iron Ladder

Use REI to look up **uses** for the following:
- Knightmetal Ingot
- Carminite

Use REI to view stonecutter recipes from Twilight Forest.

### What You Expected

All of the recipes mentioned above would be usable.

### What Happened Instead

None of the recipes mentioned above are usable.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by saltyseadoggo** [comment]
I found more missing recipes: Blocks of ironwood, steeleaf, knightmetal, arctic fur, carminite, knightmetal and fiery metal cannot be crafted into their component items.

**Comment by Drullkus** [comment]
Uncrafting Table's also missing
