### ISSUE TITLE
Bannister doesn't actually check for axe before changing shape

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#39]
### Fabric Loader Version

0.12.5

### Fabric API Version

0.42.1

### Cloth Config Version

5.1.40

### Twilight Forest Version

4.0.133

### Steps to Reproduce

1. place bannister
2. right click

### What You Expected

bannister would not change shape, because its tooltip says the player needs an axe to change its shape

### What Happened Instead

Bannister changes shape when right clicked with any item

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by saltyseadoggo** [comment]
Also applies to liveroots

**Comment by Drullkus** [comment]
Anything that checks against the Forge Tool Action system is in fact borked. You cannot use shears to harvest Torchberries either
