### ISSUE TITLE
Banisters drop nothing

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#4]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38

What I expected to happen:
I could obtain banisters by breaking them.

What happened instead:
Banisters drop nothing when broken. Tested on the mangrove banister, but it looked like all of them lack loot tables.

**Comment by Dragon-Seeker** [comment]
Its a WIP block so that is the reason for loot table issues

**Comment by saltyseadoggo** [comment]
This is now fixed, closing the issue
