### ISSUE TITLE
Root strands and torchberries are missing from most caves

### ISSUE THREAD

**Issue by saltyseadoggo** [TeamTwilight/twilightforest-fabric#5]
Fabric version: 0.11.6
Twilight Forest version: 4.0.51 (downloaded from the Discord server)
Fabric API version: 0.40.1
Cloth Config version: 5.0.38

What I expected to happen:
I would see root strands and torch berries throughout the twilight forest's caves.

What happened instead:
I never see root strands or torch berries in caves in the twilight forest, only in a hollow hill I found on the ceiling, which may imply that they can't generate below y 0.

**Comment by AlphaMode** [comment]
Please check if these issues occur on the forge version before reporting them here please
