### ISSUE TITLE
can't launch client

### ISSUE THREAD

**Issue by Dreeam-qwq** [TeamTwilight/twilightforest-fabric#51]
### Fabric Loader Version

0.12.5

### Fabric API Version

0.42.1+1.17

### Cloth Config Version

5.1.40

### Twilight Forest Version

4.0.136

### Client Log

https://gist.github.com/Dreeam-qwq/c4442dc1849b1a73b3a6c3214fa0fb05

### Steps to Reproduce

just launch fabric client with twilightforest-fabric

### What You Expected

the client can launch successfully.

### What Happened Instead

can't launch

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
This should be fixed in latest commit now
