### ISSUE TITLE
Update the lang files from .json to .lang 

### ISSUE THREAD

**Issue by Brandonbr1** [TeamTwilight/twilightforest-fabric#52]
Update the lang files from .json to .lang  as In more recent versions of Minecraft, LANG files have been replaced by .JSON files

source:[https://fileinfo.com/extension/lang](https://fileinfo.com/extension/lang)

**Comment by Drullkus** [comment]
Huh?

<https://github.com/TeamTwilight/twilightforest-fabric/tree/fabric/src/main/resources/assets/twilightforest/lang>

???
