### ISSUE TITLE
Crash on latest 1.18.1 dev version

### ISSUE THREAD

**Issue by TwelvianZeta** [TeamTwilight/twilightforest-fabric#54]
### Fabric Loader Version

0.12.12

### Fabric API Version

0.45.0+1.18

### Cloth Config Version

Not needed to crash, 6.1.48 in crash rep

### Twilight Forest Version

4.0.153

### Client Log

https://paste.ee/p/lN3MQ

### Crash Report (if applicable)

https://gist.github.com/TwelvianZeta/aa426c92ced6beb657621b0615410b0b

### Steps to Reproduce

1. Install twilight forest
2. Die

### What You Expected

The game doesn't die when you only boot with Twilight Forest and only Twilight Forest (as well as FAPI of course)

### What Happened Instead

Death/crash

### Additional Details

I'm pretty sure this bug is known but I wanted to report it anyways since its not logged as an open bug report.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by GizmoTheMoonPig** [comment]
did you perhaps consider that it isnt ready yet, hence why its a dev version
