### ISSUE TITLE
Enum extender mixin fail...

### ISSUE THREAD

**Issue by FluffyBumblee** [TeamTwilight/twilightforest-fabric#55]
### Fabric Loader Version

0.14.5

### Fabric API Version

0.51.1

### Cloth Config Version

cloth-config-6.2.57-fabric

### Twilight Forest Version

twilightforest-fabric-1.18.2-4.1.194

### Client Log

https://gist.github.com/FluffyBumblee/7b02513f30c7ec5d2ca29558326a0454

### Steps to Reproduce

Self-explanatory...

### What You Expected

For it to work

### What Happened Instead

Crash

### Additional Details

This isn't expected to be fixed. Just to be here anyways (Alphamode close this u if dont care its fine)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by FluffyBumblee** [comment]
How dafuq did u get cinderscapes bro?
Answer: Pull request......................

**Comment by FluffyBumblee** [comment]
[latest.log](https://github.com/TeamTwilight/twilightforest-fabric/files/8656559/latest.log)
Another instance of it happening...

**Comment by HacoKavanah** [comment]
Same keeps happening to me!

**Comment by AlphaMode** [comment]
Should be fixed in latest commit please reopen if its not
