### ISSUE TITLE
Changing diemensions is buggy

### ISSUE THREAD

**Issue by AlphaMode** [TeamTwilight/twilightforest-fabric#56]
### Fabric Loader Version

0.14.5

### Fabric API Version

0.51.1+1.18.2

### Cloth Config Version

loser

### Twilight Forest Version

4.1.204

### Steps to Reproduce

Jump through twilight portal

### What You Expected

Player would be able to interact with things in the dimension

### What Happened Instead

Player couldn't interact with anything in the dimension until the user re-logged

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by FluffyBumblee** [comment]
![image](https://user-images.githubusercontent.com/60066663/167774339-8add3620-53fd-44ee-860b-16e5ec05d3da.png)
:concern:
