### ISSUE TITLE
Tf Progression issue (fabric)

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest-fabric#58]
### Fabric Loader Version

0.13.3

### Fabric API Version

0.48.0

### Cloth Config Version

None

### Twilight Forest Version

4.1.204

### Steps to Reproduce

Step 1: Kill the Naga to unlock the Lich Tower
Step 2: Kill the Lich King

### What You Expected

To acquire the "Bring Out Your Dead" advancement and unlock the related biomes

### What Happened Instead

Did not acquire the "Bring Out Your Dead" advancement or unlock the related biomes

### Additional Details

This was done on the official test server

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Please try with latest build

**Comment by ToasterStrudel95** [comment]
> Please try with latest build

It is unchanged; still haven't gotten the advancement after killing another lich

**Comment by HacoKavanah** [comment]
Can confirm, I only get "The Silence Of The Forest" achievement.
