### ISSUE TITLE
Items not dropping upon death

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest-fabric#59]
### Fabric Loader Version

0.13.3

### Fabric API Version

0.53.0+1.18.2

### Cloth Config Version

none

### Twilight Forest Version

4.1.215

### Client Log

none

### Crash Report (if applicable)

none

### Steps to Reproduce

Die in any way

### What You Expected

Items to drop on the ground, or, if holding a charm of keeping, retaining amount of items relevant to charm of keeping tier

### What Happened Instead

No items drop at all, nor stay in inventory at all, whether or not holding a charm of keeping of any tier. They disappear from existence entirely

### Additional Details

This has not yet been tested with phantom armor

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Fixed in latest commit
