### ISSUE TITLE
Incompatibility with the mod Boats and Beeps

### ISSUE THREAD

**Issue by praus1** [TeamTwilight/twilightforest-fabric#6]
Forge version: Fabric version 0.11.7
Twilight Forest version: 4.0.59
Link to crash log: https://gist.github.com/praus1/83c8cc1ce04946f14ecfd459b25d3557

Steps to reproduce:
1. Install Twilight Forest for Fabric with the Fabric mod Boats and Beeps along with their respective dependencies. 

What I expected to happen: mod pack should launch successfully 

What happened instead: mod pack crashes before it can launch

**Comment by AlphaMode** [comment]
I cant view your crash log

**Comment by praus1** [comment]
> I cant view your crash log

Sorry about that. For some reason Pastebin was not showing it publicly, even though I set it to public. I updated the original post with a new link to a gist post: https://gist.github.com/praus1/83c8cc1ce04946f14ecfd459b25d3557

**Comment by Dragon-Seeker** [comment]
I believe this is a issue with not having Cloth Config installed, Dependency stuff needs to be worked out which I have yet to implemented.. Oops

**Comment by Dragon-Seeker** [comment]
If you could try Installing the latest version of cloth config just to confirm if it is a incompatibility or not that would be great.

**Comment by praus1** [comment]
> If you could try Installing the latest version of cloth config just to confirm if it is a incompatibility or not that would be great.

I did try that just now. Seems to be a different error this time? This is the new crash log: https://gist.github.com/praus1/5458a80d78c926e9340d7eb9f2939d41

**Comment by Dragon-Seeker** [comment]
@AlphaMode I believe there is a incompatibility in what you did for multi part entity's and the multipart [library](https://github.com/williambl/multipart-entities) that Boats and Beeps is using.

**Comment by Tamaized** [comment]
That lib is using `@Redirect` all over the place... i'd argue their mixins are garbage and this isnt our problem. My patches are meant to be as compatible as possible as long as others do the same.

**Comment by Tamaized** [comment]
well... this doesn't help either...
https://github.com/TeamTwilight/twilightforest-fabric/blob/fabric/src/main/java/twilightforest/mixin/client/EntityRenderDispatcherMixin.java#L38

**Comment by Dragon-Seeker** [comment]
Changing it to be a Inject as I say what alpha was doing

**Comment by Dragon-Seeker** [comment]
This compatibility issue may talk some time as the multipart implementation for TF was ported in a way to get working rather than being compatible so this may take some time.

**Comment by Dragon-Seeker** [comment]
For now it seems that the mod will be incompatible until a proper fix is found to get them to load together.

**Comment by praus1** [comment]
> For now it seems that the mod will be incompatible until a proper fix is found to get them to load together.

Thank you all for the work you’re doing. I’ll open a ticket on the Boats and Beeps mod as well, so they can look into it on their end.

**Comment by williambl** [comment]
> That lib is using `@Redirect` all over the place... i'd argue their mixins are garbage and this isnt our problem. My patches are meant to be as compatible as possible as long as others do the same.

Agreed, it was done for modfest and was therefore made to be developed as quickly as possible above anything else. If you'd like to replace the mixins of multipart lib with something better I'd accept the PRs, I really don't have much time to work on it or boats&beeps right now.
