### ISSUE TITLE
Crashing upon World Generation

### ISSUE THREAD

**Issue by Rage-GitHub** [TeamTwilight/twilightforest-fabric#60]
### Forge Version

N/A

### Twilight Forest Version

4.1.232

### Crash Report (if applicable)

https://gist.github.com/Rage-GitHub/895658f3fb61328e2978c021550c3616

### Steps to Reproduce

1. Install Twilight Forest on Fabric 0.14.6
2. Launch game
3. Attempt a new single player world creation
4. Notice it crashes

### What You Expected

For it to run the world creation fine and load in.

### What Happened Instead

The game crashed during or after world creation.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Rage-GitHub** [comment]
> Please keep Fabric issues to [the Fabric repository](https://github.com/TeamTwilight/twilightforest-fabric).

This issue was already reported to Fabric API and was told to be redirected to you.

**Comment by FluffyBumblebees** [comment]
If there was a "concurrent modification exception", blame C2ME and report it to ishland. If not, than Ik now c2me is not the issue.
