### ISSUE TITLE
[Fabric] Crash on startup with Create

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [TeamTwilight/twilightforest-fabric#61]
### ~~Forge~~ Fabric Version

Fabric loader 0.14.6 + API 0.54.0

### Twilight Forest Version

4.1.232

### Client Log

https://gist.github.com/Footage2-Amply-Pounce/d7668c3674573e619921c7a350d75bc2 (both latest.log and crash report and included)

### Crash Report (if applicable)

https://gist.github.com/Footage2-Amply-Pounce/d7668c3674573e619921c7a350d75bc2 (both latest.log and crash report and included)

### Steps to Reproduce

1. Simply install [Create](https://www.curseforge.com/minecraft/mc-mods/create-fabric) and The Twilight Forest and launch the game

### What You Expected

Launch without a crash.

### What Happened Instead

The game crashed.

### Additional Details

Please adjust the bug reporting template to include Fabric :)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of ~~Optifine~~ Optifabric/Sodium.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Footage2-Amply-Pounce** [comment]
> Please keep Fabric issues to [the Fabric repository](https://github.com/TeamTwilight/twilightforest-fabric).

Oh, sorry. The link on CurseForge leads here, didn't know there was a rep for Fabric specifically.

**Comment by AmonRay** [comment]
https://github.com/Fabricators-of-Create/Create/issues/347
