### ISSUE TITLE
Incompatible with BetterEnd

### ISSUE THREAD

**Issue by MaliciousZoroark** [TeamTwilight/twilightforest-fabric#62]
### Fabric Loader Version

Quilt : 0.17.0 Beta-2

### Fabric API Version

Quilted Fabric API : 1.0.0 Beta 16 + 0.53.4 - 1.18.2

### Twilight Forest Version

4.1.232

### Client Log

https://paste.ee/p/nW7u2

### Crash Report (if applicable)

https://paste.ee/p/nW7u2

### Steps to Reproduce

1. Launch game with BetterEnd

### What You Expected

Not to crash

### What Happened Instead

Crashed and blamed BetterEnd

### Additional Details

BetterEnd is not the issue, it worked fine without twifo

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by FluffyBumblebees** [comment]
Twilight forest uses fabric loader 0.14.5, quilt loader is restricted to 0.13.3. This is quilts fault

**Comment by MaliciousZoroark** [comment]
As of 0.17.0 Quilt should use Fabric Loader 0.14.6

**Comment by FluffyBumblebees** [comment]
Hmm weird crash then...

**Comment by MaliciousZoroark** [comment]
Yes, I looked at the logs and there seems to be no indicator as to why it's incompatible
