### ISSUE TITLE
[Crash] with Create's latest patch (.596)

### ISSUE THREAD

**Issue by itsdinkd** [TeamTwilight/twilightforest-fabric#64]
### Fabric Loader Version

0.14.5

### Fabric API Version

53.4

### Twilight Forest Version

4.1.232

### Client Log

https://pastebin.com/CJxznm0U

### Steps to Reproduce

1. Download latest twilight forest
2. Download latest Create
3. Launch game
4. crash

### What You Expected

Not to crash

### What Happened Instead

crash

### Additional Details

Can confirm downgrading to Create's 586 build does not crash game with twilight forest. Removing twilight forest and using create 596 does not crash game.

https://github.com/Fabricators-of-Create/Create/issues/347

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by itsdinkd** [comment]
@AlphaMode you closed it but not sure what that entails. will this be fixed? is it fixed? or not going to fix?

**Comment by FluffyBumblebees** [comment]
It will be fixed. He is probably updating porting lib

**Comment by SticksS123** [comment]
> @AlphaMode you closed it but not sure what that entails. will this be fixed? is it fixed? or not going to fix?

This bug has been reported already, you were supposed to check that it wasnt a duplicate, and it is, thats why he closed this

**Comment by itsdinkd** [comment]
> > @AlphaMode you closed it but not sure what that entails. will this be fixed? is it fixed? or not going to fix?
> 
> This bug has been reported already, you were supposed to check that it wasnt a duplicate, and it is, thats why he closed this

I did check, and its not a duplicate :)
