### ISSUE TITLE
Banner issue with other mods

### ISSUE THREAD

**Issue by Sunconure11** [TeamTwilight/twilightforest-fabric#66]
### Fabric Loader Version

0.14.6

### Fabric API Version

0.55.1+1.18.2

### Twilight Forest Version

4.1.232

### Client Log

https://github.com/Paperdomo101/lightstones/issues/10

### Crash Report (if applicable)

https://github.com/Paperdomo101/lightstones/issues/10

### Steps to Reproduce

1. Try to boot up the game
2. ???
3. Crash

### What You Expected

This to not, well, happen

### What Happened Instead

https://github.com/Paperdomo101/lightstones/issues/10

It would appear both us and Lightstones are handling banners in a way that sets it up for conflict with other mods that add banner patterns. Due to some issues unrelated to this mod though, I cannot get to fixing it up for you. Maybe this issue will provide more info instead.

### Additional Details

Change how banners are handled in the code. Look at Additional Banners

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Please give a actual log not a link to other issues

**Comment by Sunconure11** [comment]
https://pastebin.com/rEBA2hLk

Here's a log. I can recreate it.

**Comment by Sunconure11** [comment]
Created an isolated environment and was unable to replicate this.
