### ISSUE TITLE
Client can't start.

### ISSUE THREAD

**Issue by RaysFilen** [TeamTwilight/twilightforest-fabric#69]
### Fabric Loader Version

0.14.6

### Fabric API Version

0.53.3

### Twilight Forest Version

4.1.234

### Crash Report (if applicable)

https://gist.github.com/RaysFilen/e076ac1ef4f06195ac3e607038b4fec9

### Steps to Reproduce

Client just wouldn't start.

### What You Expected

A client. To work.

### What Happened Instead

Not work.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by LimeDev8756** [comment]
Same thing here

**Comment by cybercat5555** [comment]
Can confirm, this still happens in twilightforest-fabric-1.18.2-4.1.235

**Comment by cybercat5555** [comment]
> Can confirm, this still happens in twilightforest-fabric-1.18.2-4.1.235

Adding to this, installing Forge Config API Port [Fabric] does not fix the issue
