### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by humematt190** [TeamTwilight/twilightforest-fabric#7]
Forge version: fabric 0.11.7
Twilight Forest version: 4.0.59
Link to crash log: https://hastebin.com/obupixeneh.yaml

Steps to reproduce:
1. launch the game

What I expected to happen: the game would run just fine

What happened instead: the game crashed

**Comment by Dragon-Seeker** [comment]
Issue is that your missing cloth config, the latest dev build will fix this dependency issue not being there. Please install cloth config.
