### ISSUE TITLE
My modpack crashes when trying to start with your mod.

### ISSUE THREAD

**Issue by TheButterbrotMan** [TeamTwilight/twilightforest-fabric#70]
### Fabric Loader Version

0.14.6

### Fabric API Version

0.55.1+1.18.2

### Twilight Forest Version

1.18.2-4.1.232

### Client Log

https://bytebin.lucko.me/tflVtCdiii

### Steps to Reproduce

To much steps to write down here.

### What You Expected

Dont crash.

### What Happened Instead

Crash.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [ ] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by SticksS123** [comment]
Remove create
