### ISSUE TITLE
Minotaur crashes the server

### ISSUE THREAD

**Issue by Hackgaee** [TeamTwilight/twilightforest-fabric#73]
### Fabric Loader Version

0.14.5

### Fabric API Version

0.53.4+1.18.2

### Twilight Forest Version

4.1.232

### Crash Report (if applicable)

https://gist.github.com/Hackgaee/ea9526e9c1422a7bdf846f0a84aaad08

### Steps to Reproduce

1. Go to twilight forest
2. Walk around and load chunks
3. Server crashes when loading labyrinth and minotaur(deleting and re-generating the map region does not help)

### What You Expected

Normal work of mod without server crash(?)

### What Happened Instead

Server crashed

### Additional Details

The AQM 2 modpack is used, in the modpack support it was said to contact the mod developers

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Moondragon444** [comment]
I have found this same issue in my playthrough on a server, and it completely shut down our server.
