### ISSUE TITLE
[1.18.2] Uncrafter crash while uncrafting is set to be disabled

### ISSUE THREAD

**Issue by itsdinkd** [TeamTwilight/twilightforest-fabric#75]
### Fabric Loader Version

0.14.5

### Fabric API Version

53.4

### Twilight Forest Version

4.1.232

### Crash Report (if applicable)

https://pastebin.com/3k0DRcr0

### Steps to Reproduce

1. disable uncrafter
2. uncraft items one wouldn't normally uncraft (in this case, AE2 WIreless Terminal or Nomad book)
3. crash

### What You Expected

Uncrafter to not even be available, but if it was, to uncraft

### What Happened Instead

uncrafter being enabled still regardless of config and crashing server

### Additional Details

second crash log from another item a player in aqm2 dedicated server tried uncrafting, regardless of config setting

https://pastebin.com/AvMdwnQq 

![image](https://user-images.githubusercontent.com/35115304/172496814-20923164-4358-468a-ae1a-098b81261d1f.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
This seems to be the fault of `ae2wtlib`, not TF. This method is [marked as client-only](https://github.com/Mari023/AE2WirelessTerminalLibrary/blob/50d18e2e0807fbc0ab6bdc5a4db28c2900b1d15e/common/src/main/java/de/mari_023/ae2wtlib/wut/recipe/Common.java#L38) some reason.

**Comment by itsdinkd** [comment]
![image](https://user-images.githubusercontent.com/35115304/173162338-a12dca86-882d-456c-9b96-e3bf95047544.png)

https://pastebin.com/AvMdwnQq
It happens with this as well. completely different mod

**Comment by TropheusJ** [comment]
[This has the exact same issue](https://github.com/Ladysnake/Nomad-Books/blob/b4fd96f89eacbbef7fc0cd9faf61756e575f0c02/src/main/java/net/zestyblaze/nomadbooks/recipe/NomadBookHeightUpgradeRecipe.java#L83). From 1.16 -> 1.17 mojang changed how unused code is stripped out. My theory is these methods were originally stripped from servers since they were only used client side, and TF uses them on the server.

**Comment by TropheusJ** [comment]
From looking at the code, I appear to be correct. Only vanilla use is in client-only code.

**Comment by AlphaMode** [comment]
Can this issue be closed then?

**Comment by itsdinkd** [comment]
Just a weebit confused. So what is the solution here?

**Comment by TropheusJ** [comment]
The solution is to report the issue to the problematic mods. Can't be fixed on TF's side, this should be closed.

**Comment by itsdinkd** [comment]
> The solution is to report the issue to the problematic mods. Can't be fixed on TF's side, this should be closed.

**The config option does not work**, and while its not working, the crash reports above are occurring

**Comment by itsdinkd** [comment]
Reading does wonders.

**Comment by TropheusJ** [comment]
The crash is not the fault of TF, but `nomadbooks` and `ae2wtlib`. I'll look further into the config functionality.

**Comment by itsdinkd** [comment]
> The crash is not the fault of TF, but `nomadbooks` and `ae2wtlib`. I'll look further into the config functionality.

Yes I understand the crash report is due to the other mods. I have been referencing the config issue. that is all that I am trying to say.
