### ISSUE TITLE
[Crash] Using REI to view item Minoshroom model (RER)

### ISSUE THREAD

**Issue by itsdinkd** [TeamTwilight/twilightforest-fabric#76]
### Fabric Loader Version

0.14.6

### Fabric API Version

55.1

### Twilight Forest Version

4.1.232

### Crash Report (if applicable)

https://pastebin.com/QgPe7enk

### Steps to Reproduce

1. View a item using REI for Roughly enough resources to see which mob drops it
2. if the item is dropped by minoshroom and its model appears in REI's window, game crashes.

### What You Expected

not to crash but instead show the model of the entity that drops the item

### What Happened Instead

crashed

### Additional Details

Yes I understand there is a closed issue for Minoshroom, however, that crash report is for summoning the entity in game. This has to do with the entity being shown in REI.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by itsdinkd** [comment]
is there a timeline for a curseforge release on the commit?

**Comment by Tamaized** [comment]
Those commits are already on curse.

**Comment by itsdinkd** [comment]
Alpha has confirmed that they are not on curse.
