### ISSUE TITLE
Startup failure: "Could not execute entrypoint stage 'main' due to errors, provided by 'forgeconfigapiport'!"

### ISSUE THREAD

**Issue by kineticV** [TeamTwilight/twilightforest-fabric#80]
### Fabric Loader Version

0.14.7

### Fabric API Version

0.54.0+1.18.2

### Twilight Forest Version

4.1.235

### Client Log

https://gist.github.com/kineticV/227c6952a6901a1b4adf6103f97f12c4

### Steps to Reproduce

1. Install only the twilight forest and fabric api mods in the mods folder.
2. Start the fabric server

### What You Expected

Fabric server should start

### What Happened Instead

The server failed on startup. See the server log file for error details.

### Additional Details

This does not happen on the previously released fabric version of twilight forest, version 4.1.232. I followed the same steps above with version 4.1.232 with no startup errors.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by kineticV** [comment]
What is this a duplicate of? I don't see any open issues with the same error.

**Comment by AlphaMode** [comment]
The issue had already been fixed so it doesn't matter
