### ISSUE TITLE
Mixin issue involving rarity

### ISSUE THREAD

**Issue by Sunconure11** [TeamTwilight/twilightforest-fabric#81]
### Fabric Loader Version

0.14.6

### Fabric API Version

0.53.3+1.18.2

### Twilight Forest Version

4.1.235

### Client Log

https://pastebin.com/gRVW8md4

### Crash Report (if applicable)

https://pastebin.com/PKKQx4K2

### Steps to Reproduce

1. Boot up the game
2. ???
3. Get this error

### What You Expected

Game to run smoothly

### What Happened Instead

Crash

### Additional Details

I believe this issue to be triggered with mods that implement banners in a specific way.

https://github.com/Sunconure11/lightstones

I am using a 1.18.2 fork of Banners++ in Lightstones, for instance.

Without any other banner-adding mods, this bug does not fire.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
This is entirely Additional Banners fault for loading the Rarity class in a early riser I can't fix this on my end

**Comment by AlphaMode** [comment]
I suggest you open a issue on their github

**Comment by Sunconure11** [comment]
https://github.com/Darkhax-Minecraft/AdditionalBanners/blob/1.18.2/Fabric/src/main/java/net/darkhax/additionalbanners/AdditionalBannersEarlyRiser.java

https://github.com/Darkhax-Minecraft/AdditionalBanners/blob/1.18.2/Common/src/main/java/net/darkhax/additionalbanners/Content.java

https://github.com/Paperdomo101/lightstones/issues/10

https://github.com/Darkhax-Minecraft/AdditionalBanners/issues/27

I had talked to the dev, but they don’t seem to have a lot of free time.
