### ISSUE TITLE
stop posting about `=` dependencies i'm tired of incompatibliities

### ISSUE THREAD

**Issue by TehcJS** [TeamTwilight/twilightforest-fabric#82]
### Fabric Loader Version

Quilt Loader 0.17.0

### Fabric API Version

qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2

### Twilight Forest Version

1.18.2-4.1.235

### Client Log

no

### Steps to Reproduce

1. use the mod

### What You Expected

it to use qsl-1.1.0-beta.19_qfapi-1.0.0-beta.22_fapi-0.56.0_mc-1.18.2

### What Happened Instead

is it FUCKING REQUIRED `=0.53.3` WHO WHY WHY WHY AAAAAAAAAAAAAAAAAAAAAAA

### Additional Details

never use `=` depends please for the love of god

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TehcJS** [comment]
0 of the tasks are done btw, this is a scam.
I feel scammed.
I demand to see your manager.

**Comment by TehcJS** [comment]
Excuse me, why was this closed?
This is a real issue I am having.
![image](https://user-images.githubusercontent.com/18603248/174136004-6711a57c-45a7-4f35-bed1-05f5321eeaa2.png)

**Comment by AlphaMode** [comment]
It's already been fixed plus this is a duplicate issue

**Comment by TehcJS** [comment]
ah ok, thank you

**Comment by TehcJS** [comment]
ah ok, thank you
