### ISSUE TITLE
Crash on loading/generating a world (client and server)

### ISSUE THREAD

**Issue by Miwasak** [TeamTwilight/twilightforest-fabric#83]
### Fabric Loader Version

0.14.7

### Fabric API Version

0.56.0+1.18.2

### Twilight Forest Version

4.1.238

### Client Log

https://gist.github.com/Miwasak/2ba790243eee2118f4acd630ae550b39

### Crash Report (if applicable)

https://gist.github.com/Miwasak/c1a18128728ef1999fdc55236362f360

### Steps to Reproduce

1. create or join a world
2. crash

### What You Expected

joining the world

### What Happened Instead

It simply crash with the current log.

### Additional Details

 The pack work perfectly without twiligt forest. (both client and server)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
Update create
