### ISSUE TITLE
The secret treasure chests in the 2nd floor of labyrinth don't spawn loots

### ISSUE THREAD

**Issue by seanxiecn** [TeamTwilight/twilightforest-fabric#87]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.56.0+1.18.2

### Twilight Forest Version

4.1.238

### Client Log

https://gist.github.com/seanxiecn/bd26f4ea4ec386c8562b09d99c8aeb0c

### Steps to Reproduce

1.find the chest

### What You Expected

the loots are spawned

### What Happened Instead

empty chests

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
Caused by [sihywtcamc](https://www.curseforge.com/minecraft/mc-mods/sihywtcamc), it makes flame and power incompatible, which causes the loot table to fail. set `power enchant exclusive` to false in it's config.
