### ISSUE TITLE
TF breaks YIGD:Souldbound enchant

### ISSUE THREAD

**Issue by dandin87** [TeamTwilight/twilightforest-fabric#88]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.56.1+1.18.2

### Twilight Forest Version

4.1.238

### Client Log

Nothing relevant in the logs.

### Steps to Reproduce

Have both You're In Grave Danger and Twilight Forest mods. 
Enchant Equipment with yigd:souldbound. Die. Soulbound equipment is voided.

### What You Expected

Equipment enchanted with Soulbound to stay on player after death.

### What Happened Instead

Equipment enchanted with Soulbound was voided.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
This was fixed in the latest upstream merge.
