### ISSUE TITLE
Multipart entity's can't be meleed

### ISSUE THREAD

**Issue by AlphaMode** [TeamTwilight/twilightforest-fabric#9]

**Comment by Dragon-Seeker** [comment]
This should be fixed after replacing a patch with a mixin, as it seem to be causing the issue where the entity would return null for hydra when attempting to gather such within the server side packet which seemed to be the issue

**Comment by Dragon-Seeker** [comment]
Sadly it seems to be fixed on the dev environment allowing for melees attacks to hit but for some reason, Non Dev environments don't work and arrows seem to also be effected
