### ISSUE TITLE
Cosmetic armor renders incorrectly

### ISSUE THREAD

**Issue by Kuggle01** [TeamTwilight/twilightforest-fabric#92]
### Fabric Loader Version

0.14.7

### Fabric API Version

0.55.1+1.18.2

### Twilight Forest Version

Twilight Forest - Fabric - MC 1.18.2 - 4.1.238

### Client Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

Self exsplantory

### What You Expected

The armor to render as intended

### What Happened Instead

![image](https://user-images.githubusercontent.com/77563171/175795676-2890e17c-5d2c-4412-af14-7ff2e139c221.png)
It rendered like this when equpied in the cosmetic slots from this mod: https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-fabric

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
merging this with #74
