### ISSUE TITLE
Exception in server tick loop

### ISSUE THREAD

**Issue by TheButterbrotMan** [TeamTwilight/twilightforest-fabric#93]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.56.1+1.18.2

### Twilight Forest Version

1.18.2-4.1.238

### Crash Report (if applicable)

https://bytebin.lucko.me/6KTfLtfTK7

### Steps to Reproduce

1. Open Uncraftingtable
2. Put glass on it

### What You Expected

To not crash

### What Happened Instead

Crashing

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [ ] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TropheusJ** [comment]
Problem with Culinaire, issue made: https://github.com/DawnTeamMC/Culinaire/issues/44
