### ISSUE TITLE
Magic maps sometimes fill in background color with only black

### ISSUE THREAD

**Issue by ToasterStrudel95** [TeamTwilight/twilightforest-fabric#94]
### Fabric Loader Version

0.14.7

### Fabric API Version

0.56.0+1,18,2

### Twilight Forest Version

4.1.251

### Client Log

None

### Crash Report (if applicable)

None

### Steps to Reproduce

Use a blank magic map in the twilight forest

### What You Expected

For the magic map to display certain background colors to represent biomes

### What Happened Instead

Magic map will sometimes only fill in with a black background color. It is map ID-specific, (making multiples of the same area will do the same thing) and only seems to happen to some map IDs

### Additional Details

None

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ToasterStrudel95** [comment]
I switched to the latest version of fabric (0.41.8) and fabric api (0.57.0) and the maps resumed working properly

**Comment by ToasterStrudel95** [comment]
> 

Nevermind, it just seems the problem goes back and forth

**Comment by TropheusJ** [comment]
Can't reproduce. Maybe fixed, maybe an incompat. If it still happens on new versions, let me know, and give me a seed and position to test as well as mod list.
