### ISSUE TITLE
Darkwood leave can spread flame

### ISSUE THREAD

**Issue by August7** [TeamTwilight/twilightforest-fabric#95]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.57.0+1.18.2

### Twilight Forest Version

4.1.251

### Steps to Reproduce

light darkwood leaves

### What You Expected

fire does not spread

### What Happened Instead

![11](https://user-images.githubusercontent.com/8176495/177962546-c99ce53f-ff80-4290-a6ab-ea348bdd463c.jpg)
The fire will spread throughout the forest

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by AlphaMode** [comment]
I believe this was fixed a few commits back feel free to reopen the issue if it still occurs
