### ISSUE TITLE
Crash on using Blank Magic/Maze Map...EDIT: CAUSED BY MAP ATLASES (FABRIC)

### ISSUE THREAD

**Issue by KxttyKxt** [TeamTwilight/twilightforest-fabric#98]
### Fabric Loader Version

0.14.8

### Fabric API Version

0.57.0+1.18.2

### Twilight Forest Version

4.1.251

### Client Log

https://gist.github.com/KxttyKxt/a4bfc13c67bb36dbf7cf197ffd0d3b19

### Crash Report (if applicable)

https://gist.github.com/KxttyKxt/9365e0374c78648ecdbfc7b09a5e5336

### Steps to Reproduce

Obtain a Blank Magic Map, then use it. Instead of generating a texture, the game will crash.

### What You Expected

I expected the Magic Map to become filled in with surrounding biomes and boss/structure icons, as normal.

### What Happened Instead

The game instantly crashed, and did not load the map texture. Now, since the game crashed with the map in my hand, this world is no longer usable as it crashes any time I attempt to open it.

### Additional Details

The game instantly crashed, and did not load the map texture. Now, since the game crashed with the map in my hand, this world is no longer usable as it crashes any time I attempt to open it.

The mod "Not Enough Crashes" alters the latest.log output for the crash/error, however the actual crash log remains the same.

You can also view the crash log on [Crashy.net](https://crashy.net/uZkvAwrIXyEZmCzXc1Id).

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the forge version (If it does please report to **[here](https://github.com/TeamTwilight/twilightforest/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by mmaniac01** [comment]
I have discovered this is a fatal error with a mixin from the Map Atlases mod. I do not know the exact details, but I figured that much out.

**Comment by AlphaMode** [comment]
I think this has already been fixed on there end
